!=======================================================================
! Generated by: BlackBox Using PSCAD v5.0.0.0
!-----------------------------------------------------------------------
! Component     : CurrentConversion_1_2
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Blackbox_CurrentConversion_1_2Dyn(Iarm, Io_dq0,        &
     &   Ic_dq0, thetaPLL)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    TRDQO         ! DQ0 transformation

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Iarm(6), thetaPLL
      REAL,    INTENT(OUT) :: Io_dq0(3)
      REAL,    INTENT(OUT) :: Ic_dq0(3)

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     Ioc, Iuc, Ilc, RT_7, Icc, Iob, Iub
      REAL     Ilb, RT_8, Icb, Ica, RT_9, Iua
      REAL     Ila, Ioa, RT_10, twoTheta

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 36
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 

      Iua = Iarm(1)

! 30:[datatap] Scalar/Array Tap 

      Iub = Iarm(2)

! 40:[datatap] Scalar/Array Tap 

      Iuc = Iarm(3)

! 50:[datatap] Scalar/Array Tap 

      Ila = Iarm(4)

! 60:[datatap] Scalar/Array Tap 

      Ilb = Iarm(5)

! 70:[datatap] Scalar/Array Tap 

      Ilc = Iarm(6)

! 90:[gain] Gain Block 

!  Gain
      RT_10 = -2.0 * thetaPLL

! 100:[angle_resolver] Angle Resolver 

      twoTheta = ATAN2(SIN(RT_10),COS(RT_10))
      IF (twoTheta .LE. 0.0) THEN
        twoTheta = twoTheta + TWO_PI
      ENDIF

! 110:[sumjct] Summing/Differencing Junctions 

      Ioa = + Iua - Ila

! 120:[sumjct] Summing/Differencing Junctions 

      RT_9 = + Iua + Ila

! 130:[gain] Gain Block 

!  Gain
      Ica = 0.5 * RT_9

! 140:[sumjct] Summing/Differencing Junctions 

      Iob = + Iub - Ilb

! 150:[sumjct] Summing/Differencing Junctions 

      RT_8 = + Iub + Ilb

! 160:[gain] Gain Block 

!  Gain
      Icb = 0.5 * RT_8

! 170:[sumjct] Summing/Differencing Junctions 

      Ioc = + Iuc - Ilc

! 180:[sumjct] Summing/Differencing Junctions 

      RT_7 = + Iuc + Ilc

! 190:[gain] Gain Block 

!  Gain
      Icc = 0.5 * RT_7

! 200:[abcdq0] abc dq0 transformation 

!ABC to DQ0 transformation
      CALL TRDQO(Ioa,Iob,Ioc,RT_4,RT_5,RT_6,thetaPLL,1)

! 210:[abcdq0] abc dq0 transformation 

!ABC to DQ0 transformation
      CALL TRDQO(Ica,Icb,Icc,RT_1,RT_2,RT_3,twoTheta,1)

! 220:[datamerge] Merges data signals into an array 

      Io_dq0(1) = RT_4
      Io_dq0(2) = RT_5
      Io_dq0(3) = RT_6

! 230:[datamerge] Merges data signals into an array 

      Ic_dq0(1) = RT_1
      Ic_dq0(2) = RT_2
      Ic_dq0(3) = RT_3

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Io_dq0   is output
      !Ic_dq0   is output

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_CurrentConversion_1_2Out()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 36
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_CurrentConversion_1_2Dyn_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! BlackBox generated rtc passive branch calls 
!---------------------------------------

! 1:[rtcbranch] Runtime Configurable Passive Branch
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 


! 30:[datatap] Scalar/Array Tap 


! 40:[datatap] Scalar/Array Tap 


! 50:[datatap] Scalar/Array Tap 


! 60:[datatap] Scalar/Array Tap 


! 70:[datatap] Scalar/Array Tap 


! 90:[gain] Gain Block 


! 100:[angle_resolver] Angle Resolver 


! 110:[sumjct] Summing/Differencing Junctions 


! 120:[sumjct] Summing/Differencing Junctions 


! 130:[gain] Gain Block 


! 140:[sumjct] Summing/Differencing Junctions 


! 150:[sumjct] Summing/Differencing Junctions 


! 160:[gain] Gain Block 


! 170:[sumjct] Summing/Differencing Junctions 


! 180:[sumjct] Summing/Differencing Junctions 


! 190:[gain] Gain Block 


! 200:[abcdq0] abc dq0 transformation 


! 210:[abcdq0] abc dq0 transformation 


! 220:[datamerge] Merges data signals into an array 


! 230:[datamerge] Merges data signals into an array 


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_CurrentConversion_1_2Out_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


      RETURN
      END

