!=======================================================================
! Generated by: BlackBox Using PSCAD v5.0.0.0
!-----------------------------------------------------------------------
! Component     : MMC_Averaged_2_2
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Blackbox_MMC_Averaged_2_2Dyn(Pref, Qref, Larm, Rarm,   &
     &   Sbase, Vbase, Vbase_DC, Kpp, Kip, Kpq, Kiq, Kp, Ki, Kpc, Kic,  &
     &   N, Csm, Ltrafo_pu, Rtrafo_pu, KpPLL, KiPLL, t_rst,             &
     &   Vtr_pri_LL_RMS, Vtr_sec_LL_RMS, BR_IDX, ND_IDX, TX_IDX, SS)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    TRDQO         ! DQ0 transformation
      REAL    LIMIT         ! Hard Limiter

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Pref, Qref, Larm
      REAL,    INTENT(IN)  :: Rarm, Sbase, Vbase
      REAL,    INTENT(IN)  :: Vbase_DC, Kpp, Kip
      REAL,    INTENT(IN)  :: Kpq, Kiq, Kp, Ki
      REAL,    INTENT(IN)  :: Kpc, Kic, N, Csm
      REAL,    INTENT(IN)  :: Ltrafo_pu
      REAL,    INTENT(IN)  :: Rtrafo_pu, KpPLL
      REAL,    INTENT(IN)  :: KiPLL, t_rst
      REAL,    INTENT(IN)  :: Vtr_pri_LL_RMS
      REAL,    INTENT(IN)  :: Vtr_sec_LL_RMS
      INTEGER, INTENT(INOUT) :: BR_IDX, ND_IDX, TX_IDX, SS

! Control Signals
      REAL     Iodref_2, Ioqref_2, Qref_pu
      REAL     Qmeas_2, Io_dq_pu_2(2), RT_1(2)
      REAL     RT_2(2), Vpcc_dq_pu_2(2), RT_3(2)
      REAL     RT_4, RT_5(2), RT_6(2)
      REAL     Vpcc_q_pu_2, V_dc_pu_2
      REAL     Iarm_pu_2(6), Vpcc_2(3), RT_7(3)
      REAL     RT_8(3), RT_9(6), Vcap_l_2(3)
      REAL     Vcu_a2, Vcu_b2, Vcu_c2
      REAL     Vcap_u_2(3), RT_10, RT_11, RT_12
      REAL     RT_13, RT_14, Vpcc_d_pu_2, RT_15
      REAL     Iu_a_2, Iu_b_2, Iu_c_2, Il_a_2
      REAL     Il_b_2, Il_c_2, Iarm_2(6), RT_16
      REAL     thetaPLL_2, RT_17, RT_18, RT_19
      REAL     RT_20, RT_21, RT_22, RT_23, RT_24
      REAL     RT_25, RT_26, RT_27, RT_28, RT_29
      REAL     RT_30, RT_31, nDelta_c_2
      REAL     nSigma_c_2, nDelta_b_2, nSigma_b_2
      REAL     nDelta_a_2, nSigma_a_2, RT_32
      REAL     RT_33, RT_34, Nua_2, Nub_2, Nuc_2
      REAL     Nla_2, Nlb_2, Nlc_2, RT_35(6)
      REAL     RT_36(6), Vu_a_2, Vu_b_2, Vu_c_2
      REAL     Vl_a_2, Vl_b_2, Vl_c_2, twoTheta_2
      REAL     RT_37(3), iBaseConv, RT_38(2)
      REAL     vBaseConv, RT_39(3), Vpcc_pu_2(3)
      REAL     vPCC_scale, RT_40, RT_41
      REAL     VMMC2_sec, RT_42, RT_43, RT_44
      REAL     V_dc_2, overmodulation, Vcl_a2
      REAL     Vcl_b2, Vcl_c2, Icd_2, Icq_2
      REAL     Ic0_2, Iod_2, Ioq_2, Io0_2
      REAL     wL_pu_2(2), w2La_pu_2, wLeq_pu_2
      REAL     Pref_pu, Pmeas_2, Idc_2

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF, BRRTCI, NDRTCI, ITX, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 183

! Increment electrical object indices

      BRRTCI    = BR_IDX
      BR_IDX    = BR_IDX + 31
      NDRTCI    = ND_IDX
      ND_IDX    = ND_IDX + 23
      ITX       = TX_IDX
      TX_IDX    = TX_IDX + 3

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Vpcc_q_pu_2 = STXFRF(ISTXFRF + 43)
      RT_10    = STXFRF(ISTXFRF + 75)
      RT_11    = STXFRF(ISTXFRF + 76)
      Iu_a_2   = STXFRF(ISTXFRF + 82)
      Iu_b_2   = STXFRF(ISTXFRF + 83)
      Iu_c_2   = STXFRF(ISTXFRF + 84)
      Il_a_2   = STXFRF(ISTXFRF + 85)
      Il_b_2   = STXFRF(ISTXFRF + 86)
      Il_c_2   = STXFRF(ISTXFRF + 87)
      RT_31    = STXFRF(ISTXFRF + 110)
      RT_34    = STXFRF(ISTXFRF + 119)
      RT_40    = STXFRF(ISTXFRF + 159)
      VMMC2_sec = STXFRF(ISTXFRF + 161)
      RT_43    = STXFRF(ISTXFRF + 163)
      RT_44    = STXFRF(ISTXFRF + 164)
      V_dc_2   = STXFRF(ISTXFRF + 165)
      Idc_2    = STXFRF(ISTXFRF + 182)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vpcc_2(IT_0) = STXFRF(ISTXFRF + 50 + IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         Iarm_2(IT_0) = STXFRF(ISTXFRF + 87 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[const] Real Constant 

      RT_31 = 0.0

! 40:[const] Real Constant 

      RT_11 = 0.0

! 60:[const] Real Constant 

      RT_10 = 0.0

! 100:[datamerge] Merges data signals into an array 

      RT_6(1) = RT_11
      RT_6(2) = RT_10

! 140:[const] Real Constant 

      RT_34 = 1.0

! 320:[div] Divider 

      IF (ABS(Sbase) .LT. 1.0E-100) THEN
         IF (Sbase .LT. 0.0)  THEN
            Pref_pu = -1.0E100 * Pref
         ELSE
            Pref_pu =  1.0E100 * Pref
         ENDIF
      ELSE
         Pref_pu = Pref / Sbase
      ENDIF

! 350:[div] Divider 

      IF (ABS(Sbase) .LT. 1.0E-100) THEN
         IF (Sbase .LT. 0.0)  THEN
            Qref_pu = -1.0E100 * Qref
         ELSE
            Qref_pu =  1.0E100 * Qref
         ENDIF
      ELSE
         Qref_pu = Qref / Sbase
      ENDIF

! 380:[xfmr-3p2w] 3 Phase 2 Winding Transformer 

!  TRANSFORMER SATURATION SUBROUTINE
      IVD1_1 = NEXC
      CALL TSAT2_EXE((ITX+1),(ITX+2),(ITX+3),RTCI(BRRTCI+12),RTCI(BRRTCI&
     &+11),RTCI(BRRTCI+10),RTCI(BRRTCI+9),RTCI(BRRTCI+8),RTCI(BRRTCI+7),&
     &0,0,0,0,0,0,SS,0,1.0,0)

! 400:[emtconst] Commonly Used Constants (pi...) 

      RT_40 = SQRT_2

! 410:[emtconst] Commonly Used Constants (pi...) 

      RT_43 = SQRT_3

! 470:[div] Divider 

      IF (ABS(Vtr_pri_LL_RMS) .LT. 1.0E-100) THEN
         IF (Vtr_pri_LL_RMS .LT. 0.0)  THEN
            vPCC_scale = -1.0E100 * Vtr_sec_LL_RMS
         ELSE
            vPCC_scale =  1.0E100 * Vtr_sec_LL_RMS
         ENDIF
      ELSE
         vPCC_scale = Vtr_sec_LL_RMS / Vtr_pri_LL_RMS
      ENDIF

! 480:[mult] Multiplier 

      RT_41 = VMMC2_sec * RT_40

! 490:[div] Divider 

      IF (ABS(RT_43) .LT. 1.0E-100) THEN
         IF (RT_43 .LT. 0.0)  THEN
            RT_42 = -1.0E100 * RT_41
         ELSE
            RT_42 =  1.0E100 * RT_41
         ENDIF
      ELSE
         RT_42 = RT_41 / RT_43
      ENDIF

! 500:[Blackbox_PerUnit_2_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 2060314725)
      CALL Blackbox_PerUnit_2_3Dyn(wL_pu_2, V_dc_pu_2, Vpcc_pu_2, Iarm_p&
     &u_2, V_dc_2, Vpcc_2, Iarm_2, vBaseConv, iBaseConv, Ltrafo_pu, Vbas&
     &e_DC, Sbase, Larm, Vbase)
!

! 510:[datatap] Scalar/Array Tap 

      wLeq_pu_2 = wL_pu_2(1)

! 520:[datatap] Scalar/Array Tap 

      w2La_pu_2 = wL_pu_2(2)

! 530:[gain] Gain Block 

!  Gain
      RT_4 = -1.0 * w2La_pu_2

! 540:[gain] Gain Block 

!  Gain
      RT_39 = vPCC_scale * Vpcc_pu_2

! 550:[datatap] Scalar/Array Tap 

      RT_12 = RT_39(1)

! 560:[datatap] Scalar/Array Tap 

      RT_13 = RT_39(2)

! 570:[datatap] Scalar/Array Tap 

      RT_14 = RT_39(3)

! 580:[Blackbox_PLL_2_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 1880310503)
      CALL Blackbox_PLL_2_3Dyn(thetaPLL_2, Vpcc_q_pu_2, KpPLL, KiPLL)
!

! 590:[abcdq0] abc dq0 transformation 

!ABC to DQ0 transformation
      CALL TRDQO(RT_12,RT_13,RT_14,Vpcc_d_pu_2,Vpcc_q_pu_2,RT_15,thetaPL&
     &L_2,1)

! 600:[Blackbox_CurrentConversion_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1330809702)
      CALL Blackbox_CurrentConversion_1_2Dyn(Iarm_pu_2, RT_7, RT_8, thet&
     &aPLL_2)
!

! 610:[datatap] Scalar/Array Tap 

      Ioq_2 = RT_7(2)

! 620:[mult] Multiplier 

      RT_37 = RT_8 * iBaseConv

! 630:[datatap] Scalar/Array Tap 

      Iod_2 = RT_7(1)

! 640:[datatap] Scalar/Array Tap 

      Icq_2 = RT_37(2)

! 650:[datatap] Scalar/Array Tap 

      Icd_2 = RT_37(1)

! 660:[datamerge] Merges data signals into an array 

      Io_dq_pu_2(1) = Iod_2
      Io_dq_pu_2(2) = Ioq_2

! 670:[datamerge] Merges data signals into an array 

      Vpcc_dq_pu_2(1) = Vpcc_d_pu_2
      Vpcc_dq_pu_2(2) = Vpcc_q_pu_2

! 680:[Blackbox_PowerMeas_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1352931081)
      CALL Blackbox_PowerMeas_1_2Dyn(Qmeas_2, Pmeas_2, Io_dq_pu_2, Vpcc_&
     &dq_pu_2)
!

! 690:[datamerge] Merges data signals into an array 

      RT_5(1) = Icd_2
      RT_5(2) = Icq_2

! 700:[Blackbox_PowerCtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 105163036)
      CALL Blackbox_PowerCtrl_1_3Dyn(Ioqref_2, Qmeas_2, Qref_pu, Kpq, Ki&
     &q, t_rst)
!

! 710:[Blackbox_PControl_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 165940528)
      CALL Blackbox_PControl_1_2Dyn(Iodref_2, Pmeas_2, Pref_pu, Kpp, Kip&
     &, t_rst)
!

! 720:[datamerge] Merges data signals into an array 

      RT_2(1) = Iodref_2
      RT_2(2) = Ioqref_2

! 730:[Blackbox_PICtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 239797608)
      CALL Blackbox_PICtrl_1_3Dyn(RT_3, V_dc_pu_2, RT_4, RT_5, RT_6, RT_&
     &6, Kpc, Kic, t_rst)
!

! 740:[gain] Gain Block 

!  Gain
      RT_16 = -2.0 * thetaPLL_2

! 750:[Blackbox_PICtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 203256802)
      CALL Blackbox_PICtrl_1_3Dyn(RT_1, V_dc_pu_2, wLeq_pu_2, Io_dq_pu_2&
     &, RT_2, Vpcc_dq_pu_2, Kp, Ki, t_rst)
!

! 760:[mult] Multiplier 

      RT_38 = RT_1 * vBaseConv

! 770:[datatap] Scalar/Array Tap 

      RT_33 = RT_3(2)

! 780:[datatap] Scalar/Array Tap 

      RT_32 = RT_3(1)

! 790:[angle_resolver] Angle Resolver 

      twoTheta_2 = ATAN2(SIN(RT_16),COS(RT_16))
      IF (twoTheta_2 .LE. 0.0) THEN
        twoTheta_2 = twoTheta_2 + TWO_PI
      ENDIF

! 800:[datatap] Scalar/Array Tap 

      RT_30 = RT_38(2)

! 810:[datatap] Scalar/Array Tap 

      RT_29 = RT_38(1)

! 820:[abcdq0] abc dq0 transformation 

!DQ0 to ABC transformation
      CALL TRDQO(nSigma_a_2,nSigma_b_2,nSigma_c_2,RT_32,RT_33,RT_34,twoT&
     &heta_2,-1)

! 830:[abcdq0] abc dq0 transformation 

!DQ0 to ABC transformation
      CALL TRDQO(nDelta_a_2,nDelta_b_2,nDelta_c_2,RT_29,RT_30,RT_31,thet&
     &aPLL_2,-1)

! 840:[sumjct] Summing/Differencing Junctions 

      RT_20 = - nDelta_b_2 + nSigma_b_2

! 850:[sumjct] Summing/Differencing Junctions 

      RT_26 = + nDelta_b_2 + nSigma_b_2

! 860:[sumjct] Summing/Differencing Junctions 

      RT_22 = - nDelta_a_2 + nSigma_a_2

! 870:[sumjct] Summing/Differencing Junctions 

      RT_28 = + nDelta_a_2 + nSigma_a_2

! 880:[sumjct] Summing/Differencing Junctions 

      RT_18 = - nDelta_c_2 + nSigma_c_2

! 890:[sumjct] Summing/Differencing Junctions 

      RT_24 = + nDelta_c_2 + nSigma_c_2

! 900:[gain] Gain Block 

!  Gain
      RT_19 = 0.5 * RT_20

! 910:[gain] Gain Block 

!  Gain
      RT_25 = 0.5 * RT_26

! 920:[gain] Gain Block 

!  Gain
      RT_21 = 0.5 * RT_22

! 930:[gain] Gain Block 

!  Gain
      RT_27 = 0.5 * RT_28

! 940:[gain] Gain Block 

!  Gain
      RT_17 = 0.5 * RT_18

! 950:[gain] Gain Block 

!  Gain
      RT_23 = 0.5 * RT_24

! 960:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nlb_2 = LIMIT(0.0, 1.0, RT_19)
      ELSE
        Nlb_2 = RT_19
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,1155788372,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 970:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nub_2 = LIMIT(0.0, 1.0, RT_25)
      ELSE
        Nub_2 = RT_25
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,2028135722,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 980:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nla_2 = LIMIT(0.0, 1.0, RT_21)
      ELSE
        Nla_2 = RT_21
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,952711809,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 990:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nua_2 = LIMIT(0.0, 1.0, RT_27)
      ELSE
        Nua_2 = RT_27
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,1819758986,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 1000:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nlc_2 = LIMIT(0.0, 1.0, RT_17)
      ELSE
        Nlc_2 = RT_17
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,860953062,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 1010:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nuc_2 = LIMIT(0.0, 1.0, RT_23)
      ELSE
        Nuc_2 = RT_23
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,1417045858,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 1020:[datamerge] Merges data signals into an array 

      RT_9(1) = Nua_2
      RT_9(2) = Nub_2
      RT_9(3) = Nuc_2
      RT_9(4) = Nla_2
      RT_9(5) = Nlb_2
      RT_9(6) = Nlc_2

! 1030:[Blackbox_ArmVoltage_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 500390663)
      CALL Blackbox_ArmVoltage_1_3Dyn(RT_35, RT_36, RT_9, Iarm_2, N, Csm&
     &)
!

! 1040:[datatap] Scalar/Array Tap 

      Vl_c_2 = RT_36(6)

! 1050:[datatap] Scalar/Array Tap 

      Vl_b_2 = RT_36(5)

! 1060:[datatap] Scalar/Array Tap 

      Vl_a_2 = RT_36(4)

! 1070:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vl_c_2
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+18),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1080:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vl_b_2
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+17),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1090:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vl_a_2
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+16),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1100:[datatap] Scalar/Array Tap 

      Vcl_c2 = RT_35(6)

! 1110:[datatap] Scalar/Array Tap 

      Vcl_b2 = RT_35(5)

! 1120:[datatap] Scalar/Array Tap 

      Vcl_a2 = RT_35(4)

! 1130:[div] Divider 

      IF (ABS(RT_44) .LT. 1.0E-100) THEN
         IF (RT_44 .LT. 0.0)  THEN
            overmodulation = -1.0E100 * RT_42
         ELSE
            overmodulation =  1.0E100 * RT_42
         ENDIF
      ELSE
         overmodulation = RT_42 / RT_44
      ENDIF

! 1140:[datatap] Scalar/Array Tap 

      Vcu_c2 = RT_35(3)

! 1150:[datatap] Scalar/Array Tap 

      Vu_c_2 = RT_36(3)

! 1160:[datatap] Scalar/Array Tap 

      Vcu_b2 = RT_35(2)

! 1170:[datatap] Scalar/Array Tap 

      Vu_b_2 = RT_36(2)

! 1180:[datatap] Scalar/Array Tap 

      Vcu_a2 = RT_35(1)

! 1190:[datatap] Scalar/Array Tap 

      Vu_a_2 = RT_36(1)

! 1200:[datamerge] Merges data signals into an array 

      Vcap_l_2(1) = Vcl_a2
      Vcap_l_2(2) = Vcl_b2
      Vcap_l_2(3) = Vcl_c2

! 1210:[datamerge] Merges data signals into an array 

      Vcap_u_2(1) = Vcu_a2
      Vcap_u_2(2) = Vcu_b2
      Vcap_u_2(3) = Vcu_c2

! 1220:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vu_c_2
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+15),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1230:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vu_b_2
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+14),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1240:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vu_a_2
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+13),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1250:[datatap] Scalar/Array Tap 

      Ic0_2 = RT_37(3)

! 1260:[datatap] Scalar/Array Tap 

      Io0_2 = RT_7(3)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 43) = Vpcc_q_pu_2
      STXFRF(ISTXFRF + 75) = RT_10
      STXFRF(ISTXFRF + 76) = RT_11
      STXFRF(ISTXFRF + 82) = Iu_a_2
      STXFRF(ISTXFRF + 83) = Iu_b_2
      STXFRF(ISTXFRF + 84) = Iu_c_2
      STXFRF(ISTXFRF + 85) = Il_a_2
      STXFRF(ISTXFRF + 86) = Il_b_2
      STXFRF(ISTXFRF + 87) = Il_c_2
      STXFRF(ISTXFRF + 110) = RT_31
      STXFRF(ISTXFRF + 119) = RT_34
      STXFRF(ISTXFRF + 159) = RT_40
      STXFRF(ISTXFRF + 161) = VMMC2_sec
      STXFRF(ISTXFRF + 163) = RT_43
      STXFRF(ISTXFRF + 164) = RT_44
      STXFRF(ISTXFRF + 165) = V_dc_2
      STXFRF(ISTXFRF + 182) = Idc_2

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STXFRF(ISTXFRF + 50 + IT_0) = Vpcc_2(IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         STXFRF(ISTXFRF + 87 + IT_0) = Iarm_2(IT_0)
      END DO

!---------------------------------------
! Transfer to Exports
!---------------------------------------

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_MMC_Averaged_2_2Out(                          &
     &   BR_IDX, ND_IDX, TX_IDX, SS)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
      REAL    VM3PH2        ! '3 Phase RMS Voltage Measurement'

!---------------------------------------
! Declarations 
!---------------------------------------

      INTEGER, INTENT(INOUT) :: BR_IDX, ND_IDX, TX_IDX, SS

! Control Signals
      REAL     Vpcc_2(3), RT_10, RT_11, Iu_a_2
      REAL     Iu_b_2, Iu_c_2, Il_a_2, Il_b_2
      REAL     Il_c_2, Iarm_2(6), RT_31, RT_34
      REAL     RT_40, VMMC2_sec, RT_43, RT_44
      REAL     V_dc_2, Idc_2

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF, BRRTCI, NDRTCI, ITX, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 183

! Increment electrical object indices

      BRRTCI    = BR_IDX
      BR_IDX    = BR_IDX + 31
      NDRTCI    = ND_IDX
      ND_IDX    = ND_IDX + 23
      ITX       = TX_IDX
      TX_IDX    = TX_IDX + 3

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_10    = STXFRF(ISTXFRF + 75)
      RT_11    = STXFRF(ISTXFRF + 76)
      Iu_a_2   = STXFRF(ISTXFRF + 82)
      Iu_b_2   = STXFRF(ISTXFRF + 83)
      Iu_c_2   = STXFRF(ISTXFRF + 84)
      Il_a_2   = STXFRF(ISTXFRF + 85)
      Il_b_2   = STXFRF(ISTXFRF + 86)
      Il_c_2   = STXFRF(ISTXFRF + 87)
      RT_31    = STXFRF(ISTXFRF + 110)
      RT_34    = STXFRF(ISTXFRF + 119)
      RT_40    = STXFRF(ISTXFRF + 159)
      VMMC2_sec = STXFRF(ISTXFRF + 161)
      RT_43    = STXFRF(ISTXFRF + 163)
      RT_44    = STXFRF(ISTXFRF + 164)
      V_dc_2   = STXFRF(ISTXFRF + 165)
      Idc_2    = STXFRF(ISTXFRF + 182)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vpcc_2(IT_0) = STXFRF(ISTXFRF + 50 + IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         Iarm_2(IT_0) = STXFRF(ISTXFRF + 87 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[const] Real Constant 


      RT_31 = 0.0

! 40:[const] Real Constant 


      RT_11 = 0.0

! 60:[const] Real Constant 


      RT_10 = 0.0

! 140:[const] Real Constant 


      RT_34 = 1.0

! 260:[ammeter] Current Meter 'Iu_a_2'

      Iu_a_2 = ( CBR(RTCI(BRRTCI+0), SS))

! 280:[ammeter] Current Meter 'Idc_2'

      Idc_2 = ( CBR(RTCI(BRRTCI+6), SS))

! 290:[ammeter] Current Meter 'Iu_b_2'

      Iu_b_2 = ( CBR(RTCI(BRRTCI+1), SS))

! 310:[ammeter] Current Meter 'Iu_c_2'

      Iu_c_2 = ( CBR(RTCI(BRRTCI+2), SS))

! 360:[voltmeter] Voltmeter (Line - Line) 'V_dc_2'

      V_dc_2 = EMTDC_VVDC(SS, RTCI(NDRTCI+1), RTCI(NDRTCI+2))

! 370:[voltmetergnd] Voltmeter (Line - Ground) 'Vpcc_2'

      Vpcc_2(1) = EMTDC_VVDC(SS, RTCI(NDRTCI+3), 0)
      Vpcc_2(2) = EMTDC_VVDC(SS, RTCI(NDRTCI+4), 0)
      Vpcc_2(3) = EMTDC_VVDC(SS, RTCI(NDRTCI+5), 0)

! 390:[multimeter] Multimeter 

      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS, RTCI(NDRTCI+19), RTCI(NDRTCI+&
     &20), RTCI(NDRTCI+21), RTCF(IVD1_1+2))
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1428370531,RVD1_1,"Vd")
      VMMC2_sec = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,1428370531,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,1428370531,1,"hide2")
      ENDIF

! 400:[emtconst] Commonly Used Constants (pi...) 

      RT_40 = SQRT_2

! 410:[emtconst] Commonly Used Constants (pi...) 

      RT_43 = SQRT_3

! 420:[gain] Gain Block 

!  Gain
      RT_44 = 0.5 * V_dc_2

! 430:[ammeter] Current Meter 'Il_a_2'

      Il_a_2 = ( CBR(RTCI(BRRTCI+3), SS))

! 440:[ammeter] Current Meter 'Il_b_2'

      Il_b_2 = ( CBR(RTCI(BRRTCI+4), SS))

! 450:[ammeter] Current Meter 'Il_c_2'

      Il_c_2 = ( CBR(RTCI(BRRTCI+5), SS))

! 460:[datamerge] Merges data signals into an array 

      Iarm_2(1) = Iu_a_2
      Iarm_2(2) = Iu_b_2
      Iarm_2(3) = Iu_c_2
      Iarm_2(4) = Il_a_2
      Iarm_2(5) = Il_b_2
      Iarm_2(6) = Il_c_2

! 500:[Blackbox_PerUnit_2_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 2060314725)
      CALL Blackbox_PerUnit_2_3Out()
!

! 580:[Blackbox_PLL_2_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 1880310503)
      CALL Blackbox_PLL_2_3Out()
!

! 600:[Blackbox_CurrentConversion_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1330809702)
      CALL Blackbox_CurrentConversion_1_2Out()
!

! 680:[Blackbox_PowerMeas_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1352931081)
      CALL Blackbox_PowerMeas_1_2Out()
!

! 700:[Blackbox_PowerCtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 105163036)
      CALL Blackbox_PowerCtrl_1_3Out()
!

! 710:[Blackbox_PControl_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 165940528)
      CALL Blackbox_PControl_1_2Out()
!

! 730:[Blackbox_PICtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 239797608)
      CALL Blackbox_PICtrl_1_3Out()
!

! 750:[Blackbox_PICtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 203256802)
      CALL Blackbox_PICtrl_1_3Out()
!

! 1030:[Blackbox_ArmVoltage_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 500390663)
      CALL Blackbox_ArmVoltage_1_3Out()
!

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 75) = RT_10
      STXFRF(ISTXFRF + 76) = RT_11
      STXFRF(ISTXFRF + 82) = Iu_a_2
      STXFRF(ISTXFRF + 83) = Iu_b_2
      STXFRF(ISTXFRF + 84) = Iu_c_2
      STXFRF(ISTXFRF + 85) = Il_a_2
      STXFRF(ISTXFRF + 86) = Il_b_2
      STXFRF(ISTXFRF + 87) = Il_c_2
      STXFRF(ISTXFRF + 110) = RT_31
      STXFRF(ISTXFRF + 119) = RT_34
      STXFRF(ISTXFRF + 159) = RT_40
      STXFRF(ISTXFRF + 161) = VMMC2_sec
      STXFRF(ISTXFRF + 163) = RT_43
      STXFRF(ISTXFRF + 164) = RT_44
      STXFRF(ISTXFRF + 165) = V_dc_2
      STXFRF(ISTXFRF + 182) = Idc_2

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STXFRF(ISTXFRF + 50 + IT_0) = Vpcc_2(IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         STXFRF(ISTXFRF + 87 + IT_0) = Iarm_2(IT_0)
      END DO

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_MMC_Averaged_2_2Dyn_Begin(Sbase, Vbase,       &
     &   Vbase_DC, Kpq, Kiq, Kp, Ki, Kpc, Kic, N, Csm, Ltrafo_pu,       &
     &   Rtrafo_pu, KpPLL, KiPLL, t_rst, Vtr_pri_LL_RMS,                &
     &   Vtr_sec_LL_RMS, BR_IDX, ND_IDX, TX_IDX, SS)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Sbase, Vbase
      REAL,    INTENT(IN)  :: Vbase_DC, Kpq, Kiq
      REAL,    INTENT(IN)  :: Kp, Ki, Kpc, Kic, N
      REAL,    INTENT(IN)  :: Csm, Ltrafo_pu
      REAL,    INTENT(IN)  :: Rtrafo_pu, KpPLL
      REAL,    INTENT(IN)  :: KiPLL, t_rst
      REAL,    INTENT(IN)  :: Vtr_pri_LL_RMS
      REAL,    INTENT(IN)  :: Vtr_sec_LL_RMS
      INTEGER, INTENT(INOUT) :: BR_IDX, ND_IDX, TX_IDX, SS

! Control Signals
      REAL     RT_10, RT_11, RT_31, RT_34, RT_40
      REAL     RT_43

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4
      REAL     RVD1_5, RVD1_6

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER BRRTCI, NDRTCI, ITX, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices


! Increment electrical object indices

      BRRTCI    = BR_IDX
      BR_IDX    = BR_IDX + 31
      NDRTCI    = ND_IDX
      ND_IDX    = ND_IDX + 23
      ITX       = TX_IDX
      TX_IDX    = TX_IDX + 3

!---------------------------------------
! BlackBox generated rtc passive branch calls 
!---------------------------------------

! 1:[rtcbranch] Runtime Configurable Passive Branch
      CALL E_BRANCH_CFG(RTCI(BRRTCI+25),SS,1,1,0,1.070000,0.050000,0.000000)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+26),SS,1,1,0,1.070000,0.050000,0.000000)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+27),SS,1,1,0,1.070000,0.050000,0.000000)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+28),SS,1,1,0,1.070000,0.050000,0.000000)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+29),SS,1,1,0,1.070000,0.050000,0.000000)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+30),SS,1,1,0,1.070000,0.050000,0.000000)
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[const] Real Constant 

      RT_31 = 0.0

! 40:[const] Real Constant 

      RT_11 = 0.0

! 60:[const] Real Constant 

      RT_10 = 0.0

! 100:[datamerge] Merges data signals into an array 


! 140:[const] Real Constant 

      RT_34 = 1.0

! 320:[div] Divider 


! 350:[div] Divider 


! 380:[xfmr-3p2w] 3 Phase 2 Winding Transformer 

      CALL COMPONENT_ID(ICALL_NO,1259803488)
      RVD1_1 = ONE_3RD*1000.0
      RVD1_2 = Vtr_pri_LL_RMS*SQRT_1BY3
      RVD1_3 = Vtr_sec_LL_RMS*SQRT_1BY3
      CALL E_TF2W_CFG((ITX+1),1,RVD1_1,50.0,Ltrafo_pu,Rtrafo_pu,RVD1_2,R&
     &VD1_3,2.0)
      CALL E_TF2W_CFG((ITX+2),1,RVD1_1,50.0,Ltrafo_pu,Rtrafo_pu,RVD1_2,R&
     &VD1_3,2.0)
      CALL E_TF2W_CFG((ITX+3),1,RVD1_1,50.0,Ltrafo_pu,Rtrafo_pu,RVD1_2,R&
     &VD1_3,2.0)
      IF (0.0 .LT. 1.0E-6) THEN
        RVD1_5 = 0.0
        RVD1_6 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_6 = 0.0
        RVD1_4 = 6.0/(1000.0*RVD1_6)
        RVD1_5 = RVD1_4*RVD1_2*RVD1_2
        RVD1_6 = RVD1_4*RVD1_3*RVD1_3
        IVD1_1 = 1
      ENDIF
      CALL E_BRANCH_CFG(RTCI(BRRTCI+19),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+20),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+21),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+22),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+23),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+24),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL TSAT2_CFG(2,RTCI(BRRTCI+12),RTCI(BRRTCI+11),RTCI(BRRTCI+10),R&
     &TCI(BRRTCI+9),RTCI(BRRTCI+8),RTCI(BRRTCI+7),0,0,0,0,0,0,SS,RVD1_1,&
     &0.2,1.17,50.0,0.0,2.0,0.0,Ltrafo_pu,0.0,0.0,0.0,0.0,0.0,RVD1_2,RVD&
     &1_3,0.0,0.0)

! 400:[emtconst] Commonly Used Constants (pi...) 

      RT_40 = SQRT_2

! 410:[emtconst] Commonly Used Constants (pi...) 

      RT_43 = SQRT_3

! 470:[div] Divider 


! 480:[mult] Multiplier 


! 490:[div] Divider 


! 500:[Blackbox_PerUnit_2_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 2060314725)
      CALL Blackbox_PerUnit_2_3Dyn_Begin()
!

! 510:[datatap] Scalar/Array Tap 


! 520:[datatap] Scalar/Array Tap 


! 530:[gain] Gain Block 


! 540:[gain] Gain Block 


! 550:[datatap] Scalar/Array Tap 


! 560:[datatap] Scalar/Array Tap 


! 570:[datatap] Scalar/Array Tap 


! 580:[Blackbox_PLL_2_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 1880310503)
      CALL Blackbox_PLL_2_3Dyn_Begin()
!

! 590:[abcdq0] abc dq0 transformation 


! 600:[Blackbox_CurrentConversion_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1330809702)
      CALL Blackbox_CurrentConversion_1_2Dyn_Begin()
!

! 610:[datatap] Scalar/Array Tap 


! 620:[mult] Multiplier 


! 630:[datatap] Scalar/Array Tap 


! 640:[datatap] Scalar/Array Tap 


! 650:[datatap] Scalar/Array Tap 


! 660:[datamerge] Merges data signals into an array 


! 670:[datamerge] Merges data signals into an array 


! 680:[Blackbox_PowerMeas_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1352931081)
      CALL Blackbox_PowerMeas_1_2Dyn_Begin()
!

! 690:[datamerge] Merges data signals into an array 


! 700:[Blackbox_PowerCtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 105163036)
      CALL Blackbox_PowerCtrl_1_3Dyn_Begin()
!

! 710:[Blackbox_PControl_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 165940528)
      CALL Blackbox_PControl_1_2Dyn_Begin()
!

! 720:[datamerge] Merges data signals into an array 


! 730:[Blackbox_PICtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 239797608)
      CALL Blackbox_PICtrl_1_3Dyn_Begin()
!

! 740:[gain] Gain Block 


! 750:[Blackbox_PICtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 203256802)
      CALL Blackbox_PICtrl_1_3Dyn_Begin()
!

! 760:[mult] Multiplier 


! 770:[datatap] Scalar/Array Tap 


! 780:[datatap] Scalar/Array Tap 


! 790:[angle_resolver] Angle Resolver 


! 800:[datatap] Scalar/Array Tap 


! 810:[datatap] Scalar/Array Tap 


! 820:[abcdq0] abc dq0 transformation 


! 830:[abcdq0] abc dq0 transformation 


! 840:[sumjct] Summing/Differencing Junctions 


! 850:[sumjct] Summing/Differencing Junctions 


! 860:[sumjct] Summing/Differencing Junctions 


! 870:[sumjct] Summing/Differencing Junctions 


! 880:[sumjct] Summing/Differencing Junctions 


! 890:[sumjct] Summing/Differencing Junctions 


! 900:[gain] Gain Block 


! 910:[gain] Gain Block 


! 920:[gain] Gain Block 


! 930:[gain] Gain Block 


! 940:[gain] Gain Block 


! 950:[gain] Gain Block 


! 960:[hardlimit] Hard Limiter 


! 970:[hardlimit] Hard Limiter 


! 980:[hardlimit] Hard Limiter 


! 990:[hardlimit] Hard Limiter 


! 1000:[hardlimit] Hard Limiter 


! 1010:[hardlimit] Hard Limiter 


! 1020:[datamerge] Merges data signals into an array 


! 1030:[Blackbox_ArmVoltage_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 500390663)
      CALL Blackbox_ArmVoltage_1_3Dyn_Begin()
!

! 1040:[datatap] Scalar/Array Tap 


! 1050:[datatap] Scalar/Array Tap 


! 1060:[datatap] Scalar/Array Tap 


! 1070:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1080:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1090:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1100:[datatap] Scalar/Array Tap 


! 1110:[datatap] Scalar/Array Tap 


! 1120:[datatap] Scalar/Array Tap 


! 1130:[div] Divider 


! 1140:[datatap] Scalar/Array Tap 


! 1150:[datatap] Scalar/Array Tap 


! 1160:[datatap] Scalar/Array Tap 


! 1170:[datatap] Scalar/Array Tap 


! 1180:[datatap] Scalar/Array Tap 


! 1190:[datatap] Scalar/Array Tap 


! 1200:[datamerge] Merges data signals into an array 


! 1210:[datamerge] Merges data signals into an array 


! 1220:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1230:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1240:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1250:[datatap] Scalar/Array Tap 


! 1260:[datatap] Scalar/Array Tap 


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_MMC_Averaged_2_2Out_Begin(Sbase, Vbase,       &
     &   Vbase_DC, Kpq, Kiq, Kp, Ki, Kpc, Kic, N, Csm, Ltrafo_pu,       &
     &   Rtrafo_pu, KpPLL, KiPLL, t_rst, Vtr_pri_LL_RMS,                &
     &   Vtr_sec_LL_RMS, BR_IDX, ND_IDX, TX_IDX, SS)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Sbase, Vbase
      REAL,    INTENT(IN)  :: Vbase_DC, Kpq, Kiq
      REAL,    INTENT(IN)  :: Kp, Ki, Kpc, Kic, N
      REAL,    INTENT(IN)  :: Csm, Ltrafo_pu
      REAL,    INTENT(IN)  :: Rtrafo_pu, KpPLL
      REAL,    INTENT(IN)  :: KiPLL, t_rst
      REAL,    INTENT(IN)  :: Vtr_pri_LL_RMS
      REAL,    INTENT(IN)  :: Vtr_sec_LL_RMS
      INTEGER, INTENT(INOUT) :: BR_IDX, ND_IDX, TX_IDX, SS

! Control Signals
      REAL     RT_10, RT_11, RT_31, RT_34, RT_40
      REAL     RT_43

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER BRRTCI, NDRTCI, ITX, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices


! Increment electrical object indices

      BRRTCI    = BR_IDX
      BR_IDX    = BR_IDX + 31
      NDRTCI    = ND_IDX
      ND_IDX    = ND_IDX + 23
      ITX       = TX_IDX
      TX_IDX    = TX_IDX + 3

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[const] Real Constant 

      RT_31 = 0.0

! 40:[const] Real Constant 

      RT_11 = 0.0

! 60:[const] Real Constant 

      RT_10 = 0.0

! 140:[const] Real Constant 

      RT_34 = 1.0

! 390:[multimeter] Multimeter 

      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.0

! 400:[emtconst] Commonly Used Constants (pi...) 

      RT_40 = SQRT_2

! 410:[emtconst] Commonly Used Constants (pi...) 

      RT_43 = SQRT_3

! 420:[gain] Gain Block 


! 460:[datamerge] Merges data signals into an array 


! 500:[Blackbox_PerUnit_2_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 2060314725)
      CALL Blackbox_PerUnit_2_3Out_Begin()
!

! 580:[Blackbox_PLL_2_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 1880310503)
      CALL Blackbox_PLL_2_3Out_Begin()
!

! 600:[Blackbox_CurrentConversion_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1330809702)
      CALL Blackbox_CurrentConversion_1_2Out_Begin()
!

! 680:[Blackbox_PowerMeas_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1352931081)
      CALL Blackbox_PowerMeas_1_2Out_Begin()
!

! 700:[Blackbox_PowerCtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 105163036)
      CALL Blackbox_PowerCtrl_1_3Out_Begin()
!

! 710:[Blackbox_PControl_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 165940528)
      CALL Blackbox_PControl_1_2Out_Begin()
!

! 730:[Blackbox_PICtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 239797608)
      CALL Blackbox_PICtrl_1_3Out_Begin()
!

! 750:[Blackbox_PICtrl_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 203256802)
      CALL Blackbox_PICtrl_1_3Out_Begin()
!

! 1030:[Blackbox_ArmVoltage_1_3]  

!
      CALL COMPONENT_ID(ICALL_NO, 500390663)
      CALL Blackbox_ArmVoltage_1_3Out_Begin()
!

      RETURN
      END

