!=======================================================================
! Generated by: BlackBox Using PSCAD v5.0.0.0
!-----------------------------------------------------------------------
! Component     : PControl_1_2
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Blackbox_PControl_1_2Dyn(Iodref, Pmeas, Pref, Kp, Ki,  &
     &   t_rst)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Pmeas, Pref, Kp, Ki
      REAL,    INTENT(IN)  :: t_rst
      REAL,    INTENT(OUT) :: Iodref

! Control Signals
      INTEGER  IT_1
      REAL     RT_1, Tip, RT_2, RT_3, RT_4, RT_5
      REAL     RT_6, Rst

! Internal Variables
      REAL     RVD2_1(2), RVD1_1, RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRI, ISTXFRF, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRI   = NSTXFRI
      NSTXFRI   = NSTXFRI + 1
      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 14
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STXFRF(ISTXFRF + 6)

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[time-sig] Output of Simulation Time 

      RT_6 = TIME

! 60:[const] Real Constant 

      RT_1 = 1.0

! 80:[sumjct] Summing/Differencing Junctions 

      RT_2 = + Pref - Pmeas

! 90:[compare] Single Input Level Comparator 

!
!
      CALL EMTDC_X2COMP(0,0,t_rst,RT_6,1.0,0.0,0.0,RVD2_1)
      Rst = RVD2_1(1)

! 100:[div] Divider 

      IF (ABS(Ki) .LT. 1.0E-100) THEN
         IF (Ki .LT. 0.0)  THEN
            Tip = -1.0E100 * RT_1
         ELSE
            Tip =  1.0E100 * RT_1
         ENDIF
      ELSE
         Tip = RT_1 / Ki
      ENDIF

! 110:[inv] Interpolated Logic Inverter 

      IF (NINT(Rst) .NE. 0) THEN
         IT_1 = 0
      ELSE
         IT_1 = 1
      ENDIF

! 120:[mult] Multiplier 

      RT_3 = RT_2 * REAL(IT_1)

! 130:[gain] Gain Block 

!  Gain
      RT_5 = Kp * RT_3

! 140:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_3
      RVD2_1(2) = 0.0
      RVD2_2(1) = FLOAT(NINT(Rst))
      RVD2_2(2) = 0.0
      RT_4 = EMTDC_XINT(0, 0, 1, RVD1_1, Tip, 0.0, -1000000000.0, 100000&
     &0000.0, RVD2_2, RVD2_1)

! 150:[sumjct] Summing/Differencing Junctions 

      Iodref = + RT_5 + RT_4

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 6) = RT_1

!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Iodref   is output

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PControl_1_2Out()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Control Signals
      REAL     RT_1

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRI, ISTXFRF

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRI   = NSTXFRI
      NSTXFRI   = NSTXFRI + 1
      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 14
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STXFRF(ISTXFRF + 6)

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 60:[const] Real Constant 


      RT_1 = 1.0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 6) = RT_1

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PControl_1_2Dyn_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals
      REAL     RT_1

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! BlackBox generated rtc passive branch calls 
!---------------------------------------

! 1:[rtcbranch] Runtime Configurable Passive Branch
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[time-sig] Output of Simulation Time 


! 60:[const] Real Constant 

      RT_1 = 1.0

! 80:[sumjct] Summing/Differencing Junctions 


! 90:[compare] Single Input Level Comparator 


! 100:[div] Divider 


! 110:[inv] Interpolated Logic Inverter 


! 120:[mult] Multiplier 


! 130:[gain] Gain Block 


! 140:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 150:[sumjct] Summing/Differencing Junctions 


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PControl_1_2Out_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals
      REAL     RT_1

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 60:[const] Real Constant 

      RT_1 = 1.0

      RETURN
      END

