!=======================================================================
! Generated by: BlackBox Using PSCAD v5.0.0.0
!-----------------------------------------------------------------------
! Component     : PLL_2
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Blackbox_PLL_2Dyn(thetaPLL, Vq, Kp, Ki)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Vq, Kp, Ki
      REAL,    INTENT(OUT) :: thetaPLL

! Control Signals
      REAL     RT_1, RT_2, RT_3, Ti, RT_4, RT_5
      REAL     wg, RT_6, RT_7, RT_8, RT_9, RT_10

! Internal Variables
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 16
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_3     = STXFRF(ISTXFRF + 6)
      RT_6     = STXFRF(ISTXFRF + 11)
      RT_7     = STXFRF(ISTXFRF + 12)

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 

      RT_3 = 1.0

! 50:[gain] Gain Block 

!  Gain
      RT_8 = -1.0 * Vq

! 60:[gain] Gain Block 

!  Gain
      RT_10 = Kp * RT_8

! 70:[emtconst] Commonly Used Constants (pi...) 

      RT_6 = TWO_PI

! 80:[const] Real Constant 

      RT_7 = 50.0

! 90:[div] Divider 

      IF (ABS(Ki) .LT. 1.0E-100) THEN
         IF (Ki .LT. 0.0)  THEN
            Ti = -1.0E100 * RT_3
         ELSE
            Ti =  1.0E100 * RT_3
         ENDIF
      ELSE
         Ti = RT_3 / Ki
      ENDIF

! 100:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_8
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_9 = EMTDC_XINT(0, 0, 0, RVD1_1, Ti, 0.0, -1000000000.0, 1000000&
     &000.0, RVD2_2, RVD2_1)

! 110:[mult] Multiplier 

      wg = RT_6 * RT_7

! 120:[sumjct] Summing/Differencing Junctions 

      RT_2 = + RT_10 + RT_9

! 130:[gain] Gain Block 

!  Gain
      RT_1 = wg * RT_2

! 140:[sumjct] Summing/Differencing Junctions 

      RT_4 = + RT_1 + wg

! 150:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_4
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_5 = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -1000000000.0, 100000&
     &0000.0, RVD2_2, RVD2_1)

! 160:[angle_resolver] Angle Resolver 

      thetaPLL = ATAN2(SIN(RT_5),COS(RT_5))
      IF (thetaPLL .LE. 0.0) THEN
        thetaPLL = thetaPLL + TWO_PI
      ENDIF

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 6) = RT_3
      STXFRF(ISTXFRF + 11) = RT_6
      STXFRF(ISTXFRF + 12) = RT_7

!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !thetaPLL is output

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PLL_2Out()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Control Signals
      REAL     RT_3, RT_6, RT_7

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 16
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_3     = STXFRF(ISTXFRF + 6)
      RT_6     = STXFRF(ISTXFRF + 11)
      RT_7     = STXFRF(ISTXFRF + 12)

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 


      RT_3 = 1.0

! 70:[emtconst] Commonly Used Constants (pi...) 

      RT_6 = TWO_PI

! 80:[const] Real Constant 


      RT_7 = 50.0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 6) = RT_3
      STXFRF(ISTXFRF + 11) = RT_6
      STXFRF(ISTXFRF + 12) = RT_7

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PLL_2Dyn_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals
      REAL     RT_3, RT_6, RT_7

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! BlackBox generated rtc passive branch calls 
!---------------------------------------

! 1:[rtcbranch] Runtime Configurable Passive Branch
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 

      RT_3 = 1.0

! 50:[gain] Gain Block 


! 60:[gain] Gain Block 


! 70:[emtconst] Commonly Used Constants (pi...) 

      RT_6 = TWO_PI

! 80:[const] Real Constant 

      RT_7 = 50.0

! 90:[div] Divider 


! 100:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 110:[mult] Multiplier 


! 120:[sumjct] Summing/Differencing Junctions 


! 130:[gain] Gain Block 


! 140:[sumjct] Summing/Differencing Junctions 


! 150:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 160:[angle_resolver] Angle Resolver 


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PLL_2Out_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals
      REAL     RT_3, RT_6, RT_7

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 

      RT_3 = 1.0

! 70:[emtconst] Commonly Used Constants (pi...) 

      RT_6 = TWO_PI

! 80:[const] Real Constant 

      RT_7 = 50.0

      RETURN
      END

