!=======================================================================
! Generated by: BlackBox Using PSCAD v5.0.0.0
!-----------------------------------------------------------------------
! Component     : MMC_Averaged_1
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Blackbox_MMC_Averaged_1Dyn(Vdcref, Qref, Larm, Rarm,   &
     &   Sbase, Vbase, Vbase_DC, KpDC, KiDC, Kpq, Kiq, Kp, Ki, Kpc,     &
     &   Kic, KpPLL, KiPLL, N, Csm, Ltrafo_pu, Rtrafo_pu, t_rst,        &
     &   Vtr_pri_LL_RMS, Vtr_sec_LL_RMS, BR_IDX, ND_IDX, TX_IDX, SS)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
!     SUBR    TRDQO         ! DQ0 transformation
      REAL    LIMIT         ! Hard Limiter

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Vdcref, Qref, Larm
      REAL,    INTENT(IN)  :: Rarm, Sbase, Vbase
      REAL,    INTENT(IN)  :: Vbase_DC, KpDC
      REAL,    INTENT(IN)  :: KiDC, Kpq, Kiq, Kp
      REAL,    INTENT(IN)  :: Ki, Kpc, Kic, KpPLL
      REAL,    INTENT(IN)  :: KiPLL, N, Csm
      REAL,    INTENT(IN)  :: Ltrafo_pu
      REAL,    INTENT(IN)  :: Rtrafo_pu, t_rst
      REAL,    INTENT(IN)  :: Vtr_pri_LL_RMS
      REAL,    INTENT(IN)  :: Vtr_sec_LL_RMS
      INTEGER, INTENT(INOUT) :: BR_IDX, ND_IDX, TX_IDX, SS

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     Pmeas_1, RT_7, RT_8, RT_9
      REAL     nSigma_a_1, RT_10, nSigma_b_1
      REAL     RT_11, nSigma_c_1, RT_12, RT_13
      REAL     RT_14, RT_15, RT_16, nDelta_a_1
      REAL     nDelta_b_1, RT_17, RT_18
      REAL     nDelta_c_1, RT_19, thetaPLL_1
      REAL     Vpcc_d_pu_1, RT_20(2), RT_21
      REAL     RT_22, RT_23, RT_24, Iodref_1
      REAL     Ioqref_1, RT_25(2), Iod_1, Ioq_1
      REAL     Io_dq_pu_1(2), RT_26, RT_27
      REAL     RT_28(2), Icd_1, Icq_1, RT_29(2)
      REAL     RT_30(3), RT_31(3), RT_32(3)
      REAL     Io_AlBe0_pu_1(3), RT_33(3)
      REAL     Vcap_u_1(3), Vcl_a1, Vcl_b1
      REAL     Vcl_c1, Vcap_l_1(3), Nua_1, Nub_1
      REAL     Nuc_1, Nla_1, Nlb_1, Nlc_1
      REAL     RT_34(6), Vu_a_1, Iu_a_1, Iu_b_1
      REAL     Iu_c_1, Iarm_u_1(3), Il_a_1
      REAL     Il_b_1, Il_c_1, Iarm_l_1(3)
      REAL     RT_35(2), V_dc_pu_1, wLeq_pu_1
      REAL     Vpcc_dq_pu_1(2), RT_36(2), RT_37
      REAL     RT_38(6), RT_39(6), Iarm_1(6)
      REAL     wL_pu_1(2), Vpcc_pu_1(3)
      REAL     Iarm_pu_1(6), V_dc_1, Vpcc_1(3)
      REAL     vBaseConv, iBaseConv, Qmeas_1
      REAL     Qref_pu, Vpcc_q_pu_1, Vdcref_pu
      REAL     w2La_pu_1, twoTheta_1, RT_40, Dblk
      REAL     RT_41(2), RT_42(3), Vu_b_1, Vu_c_1
      REAL     Vl_a_1, Vl_b_1, Vl_c_1, RT_43(3)
      REAL     vPCC_scale, Io0_1, Ic0_1, Vcu_c1
      REAL     Vcu_b1, Vcu_a1, Idc_1

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4
      REAL     RVD2_1(2)

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF, BRRTCI, NDRTCI, ITX, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 195

! Increment electrical object indices

      BRRTCI    = BR_IDX
      BR_IDX    = BR_IDX + 50
      NDRTCI    = ND_IDX
      ND_IDX    = ND_IDX + 33
      ITX       = TX_IDX
      TX_IDX    = TX_IDX + 3

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_7     = STXFRF(ISTXFRF + 31)
      RT_16    = STXFRF(ISTXFRF + 43)
      RT_26    = STXFRF(ISTXFRF + 66)
      RT_27    = STXFRF(ISTXFRF + 67)
      Iu_a_1   = STXFRF(ISTXFRF + 111)
      Iu_b_1   = STXFRF(ISTXFRF + 112)
      Iu_c_1   = STXFRF(ISTXFRF + 113)
      Il_a_1   = STXFRF(ISTXFRF + 117)
      Il_b_1   = STXFRF(ISTXFRF + 118)
      Il_c_1   = STXFRF(ISTXFRF + 119)
      V_dc_1   = STXFRF(ISTXFRF + 161)
      Vpcc_q_pu_1 = STXFRF(ISTXFRF + 169)
      Idc_1    = STXFRF(ISTXFRF + 194)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Iarm_u_1(IT_0) = STXFRF(ISTXFRF + 113 + IT_0)
         Iarm_l_1(IT_0) = STXFRF(ISTXFRF + 119 + IT_0)
         Vpcc_1(IT_0) = STXFRF(ISTXFRF + 161 + IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         Iarm_1(IT_0) = STXFRF(ISTXFRF + 143 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 230:[const] Real Constant 

      RT_16 = 0.0

! 240:[const] Real Constant 

      RT_26 = 0.0

! 260:[const] Real Constant 

      RT_27 = 0.0

! 270:[div] Divider 

      IF (ABS(Sbase) .LT. 1.0E-100) THEN
         IF (Sbase .LT. 0.0)  THEN
            Qref_pu = -1.0E100 * Qref
         ELSE
            Qref_pu =  1.0E100 * Qref
         ENDIF
      ELSE
         Qref_pu = Qref / Sbase
      ENDIF

! 280:[datamerge] Merges data signals into an array 

      RT_28(1) = RT_26
      RT_28(2) = RT_27

! 320:[const] Real Constant 

      RT_7 = 1.0

! 360:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,1108376743)
      CALL E_VARRLC1_EXE(3 ,SS , RTCI(BRRTCI+7), RTCI(BRRTCI+8), Larm, 0&
     &.0)

! 370:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,432960801)
      CALL E_VARRLC1_EXE(3 ,SS , RTCI(BRRTCI+18), RTCI(BRRTCI+19), Larm,&
     & 0.0)

! 380:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,460403226)
      CALL E_VARRLC1_EXE(3 ,SS , RTCI(BRRTCI+21), RTCI(BRRTCI+22), Larm,&
     & 0.0)

! 390:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,1507969202)
      CALL E_VARRLC1_EXE(0 ,SS , RTCI(BRRTCI+9), 0, Rarm, 0.0)

! 410:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,1475521466)
      CALL E_VARRLC1_EXE(0 ,SS , RTCI(BRRTCI+20), 0, Rarm, 0.0)

! 420:[xfmr-3p2w] 3 Phase 2 Winding Transformer 

!  TRANSFORMER SATURATION SUBROUTINE
      IVD1_1 = NEXC
      CALL TSAT2_EXE((ITX+1),(ITX+2),(ITX+3),RTCI(BRRTCI+44),RTCI(BRRTCI&
     &+45),RTCI(BRRTCI+46),RTCI(BRRTCI+47),RTCI(BRRTCI+48),RTCI(BRRTCI+4&
     &9),0,0,0,0,0,0,SS,0,1.0,0)

! 440:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,195745684)
      CALL E_VARRLC1_EXE(0 ,SS , RTCI(BRRTCI+23), 0, Rarm, 0.0)

! 450:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,664460672)
      CALL E_VARRLC1_EXE(3 ,SS , RTCI(BRRTCI+24), RTCI(BRRTCI+25), Larm,&
     & 0.0)

! 460:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,1866112146)
      CALL E_VARRLC1_EXE(3 ,SS , RTCI(BRRTCI+27), RTCI(BRRTCI+28), Larm,&
     & 0.0)

! 470:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,674362871)
      CALL E_VARRLC1_EXE(3 ,SS , RTCI(BRRTCI+30), RTCI(BRRTCI+31), Larm,&
     & 0.0)

! 480:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,147052432)
      CALL E_VARRLC1_EXE(0 ,SS , RTCI(BRRTCI+26), 0, Rarm, 0.0)

! 490:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,1105025761)
      CALL E_VARRLC1_EXE(0 ,SS , RTCI(BRRTCI+29), 0, Rarm, 0.0)

! 500:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,679580652)
      CALL E_VARRLC1_EXE(0 ,SS , RTCI(BRRTCI+32), 0, Rarm, 0.0)

! 540:[time-sig] Output of Simulation Time 

      RT_40 = TIME

! 550:[compare] Single Input Level Comparator 

!
!
      CALL EMTDC_X2COMP(0,0,0.6,RT_40,0.0,0.0,1.0,RVD2_1)
      Dblk = RVD2_1(1)

! 560:[div] Divider 

      IF (ABS(Vtr_pri_LL_RMS) .LT. 1.0E-100) THEN
         IF (Vtr_pri_LL_RMS .LT. 0.0)  THEN
            vPCC_scale = -1.0E100 * Vtr_sec_LL_RMS
         ELSE
            vPCC_scale =  1.0E100 * Vtr_sec_LL_RMS
         ENDIF
      ELSE
         vPCC_scale = Vtr_sec_LL_RMS / Vtr_pri_LL_RMS
      ENDIF

! 570:[div] Divider 

      IF (ABS(Vbase_dc) .LT. 1.0E-100) THEN
         IF (Vbase_dc .LT. 0.0)  THEN
            Vdcref_pu = -1.0E100 * Vdcref
         ELSE
            Vdcref_pu =  1.0E100 * Vdcref
         ENDIF
      ELSE
         Vdcref_pu = Vdcref / Vbase_dc
      ENDIF

! 590:[Blackbox_PerUnit_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 2109480740)
      CALL Blackbox_PerUnit_2Dyn(wL_pu_1, V_dc_pu_1, Vpcc_pu_1, Iarm_pu_&
     &1, V_dc_1, Vpcc_1, Iarm_1, vBaseConv, iBaseConv, Ltrafo_pu, Vbase_&
     &dc, Sbase, Larm, Vbase)
!

! 600:[gain] Gain Block 

!  Gain
      RT_43 = vPCC_scale * Vpcc_pu_1

! 610:[datatap] Scalar/Array Tap 

      RT_21 = RT_43(1)

! 620:[datatap] Scalar/Array Tap 

      RT_22 = RT_43(2)

! 630:[datatap] Scalar/Array Tap 

      RT_23 = RT_43(3)

! 640:[datatap] Scalar/Array Tap 

      wLeq_pu_1 = wL_pu_1(1)

! 650:[datatap] Scalar/Array Tap 

      w2La_pu_1 = wL_pu_1(2)

! 660:[Blackbox_PowerCtrl_1_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1481166677)
      CALL Blackbox_PowerCtrl_1_1_2Dyn(Iodref_1, V_dc_pu_1, Vdcref_pu, K&
     &pDC, KiDC, t_rst)
!

! 670:[gain] Gain Block 

!  Gain
      RT_37 = -1.0 * w2La_pu_1

! 680:[Blackbox_PLL_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1310347230)
      CALL Blackbox_PLL_2Dyn(thetaPLL_1, Vpcc_q_pu_1, KpPLL, KiPLL)
!

! 690:[abcdq0] abc dq0 transformation 

!ABC to DQ0 transformation
      CALL TRDQO(RT_21,RT_22,RT_23,Vpcc_d_pu_1,Vpcc_q_pu_1,RT_24,thetaPL&
     &L_1,1)

! 700:[Blackbox_CurrentConversion_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 1607301208)
      CALL Blackbox_CurrentConversion_1Dyn(Iarm_pu_1, RT_30, RT_31, RT_3&
     &2, Io_AlBe0_pu_1, RT_33, thetaPLL_1)
!

! 710:[datatap] Scalar/Array Tap 

      Ioq_1 = RT_31(2)

! 720:[datatap] Scalar/Array Tap 

      Iod_1 = RT_31(1)

! 730:[datamerge] Merges data signals into an array 

      Io_dq_pu_1(1) = Iod_1
      Io_dq_pu_1(2) = Ioq_1

! 740:[mult] Multiplier 

      RT_42 = RT_33 * iBaseConv

! 750:[datamerge] Merges data signals into an array 

      RT_20(1) = Vpcc_d_pu_1
      RT_20(2) = Vpcc_q_pu_1

! 760:[gain] Gain Block 

!  Gain
      Vpcc_dq_pu_1 = 1.0 * RT_20

! 770:[Blackbox_PowerMeas_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 2045340753)
      CALL Blackbox_PowerMeas_2Dyn(Qmeas_1, Pmeas_1, Io_dq_pu_1, Vpcc_dq&
     &_pu_1)
!

! 780:[Blackbox_PowerCtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 271340115)
      CALL Blackbox_PowerCtrl_1Dyn(Ioqref_1, Qmeas_1, Qref_pu, Kpq, Kiq,&
     & t_rst)
!

! 790:[datatap] Scalar/Array Tap 

      Icq_1 = RT_42(2)

! 800:[datatap] Scalar/Array Tap 

      Icd_1 = RT_42(1)

! 810:[datamerge] Merges data signals into an array 

      RT_29(1) = Icd_1
      RT_29(2) = Icq_1

! 820:[datamerge] Merges data signals into an array 

      RT_25(1) = Iodref_1
      RT_25(2) = Ioqref_1

! 830:[Blackbox_PICtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 893673074)
      CALL Blackbox_PICtrl_1Dyn(RT_36, V_dc_pu_1, RT_37, RT_29, RT_28, R&
     &T_28, Kpc, Kic, t_rst)
!

! 840:[Blackbox_PICtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 1754685605)
      CALL Blackbox_PICtrl_1Dyn(RT_35, V_dc_pu_1, wLeq_pu_1, Io_dq_pu_1,&
     & RT_25, Vpcc_dq_pu_1, Kp, Ki, t_rst)
!

! 850:[mult] Multiplier 

      RT_41 = RT_35 * vBaseConv

! 860:[gain] Gain Block 

!  Gain
      RT_19 = -2.0 * thetaPLL_1

! 870:[datatap] Scalar/Array Tap 

      RT_9 = RT_36(2)

! 880:[datatap] Scalar/Array Tap 

      RT_8 = RT_36(1)

! 890:[datatap] Scalar/Array Tap 

      RT_18 = RT_41(2)

! 900:[datatap] Scalar/Array Tap 

      RT_17 = RT_41(1)

! 910:[angle_resolver] Angle Resolver 

      twoTheta_1 = ATAN2(SIN(RT_19),COS(RT_19))
      IF (twoTheta_1 .LE. 0.0) THEN
        twoTheta_1 = twoTheta_1 + TWO_PI
      ENDIF

! 920:[abcdq0] abc dq0 transformation 

!DQ0 to ABC transformation
      CALL TRDQO(nSigma_a_1,nSigma_b_1,nSigma_c_1,RT_8,RT_9,RT_7,twoThet&
     &a_1,-1)

! 930:[abcdq0] abc dq0 transformation 

!DQ0 to ABC transformation
      CALL TRDQO(nDelta_a_1,nDelta_b_1,nDelta_c_1,RT_17,RT_18,RT_16,thet&
     &aPLL_1,-1)

! 940:[sumjct] Summing/Differencing Junctions 

      RT_13 = - nDelta_a_1 + nSigma_a_1

! 950:[sumjct] Summing/Differencing Junctions 

      RT_10 = + nDelta_a_1 + nSigma_a_1

! 960:[sumjct] Summing/Differencing Junctions 

      RT_15 = - nDelta_c_1 + nSigma_c_1

! 970:[sumjct] Summing/Differencing Junctions 

      RT_12 = + nDelta_c_1 + nSigma_c_1

! 980:[sumjct] Summing/Differencing Junctions 

      RT_14 = - nDelta_b_1 + nSigma_b_1

! 990:[sumjct] Summing/Differencing Junctions 

      RT_11 = + nDelta_b_1 + nSigma_b_1

! 1000:[gain] Gain Block 

!  Gain
      RT_3 = 0.5 * RT_13

! 1010:[gain] Gain Block 

!  Gain
      RT_6 = 0.5 * RT_10

! 1020:[gain] Gain Block 

!  Gain
      RT_1 = 0.5 * RT_15

! 1030:[gain] Gain Block 

!  Gain
      RT_4 = 0.5 * RT_12

! 1040:[gain] Gain Block 

!  Gain
      RT_2 = 0.5 * RT_14

! 1050:[gain] Gain Block 

!  Gain
      RT_5 = 0.5 * RT_11

! 1060:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nla_1 = LIMIT(0.0, 1.0, RT_3)
      ELSE
        Nla_1 = RT_3
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,502560938,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 1070:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nua_1 = LIMIT(0.0, 1.0, RT_6)
      ELSE
        Nua_1 = RT_6
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,944471669,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 1080:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nlc_1 = LIMIT(0.0, 1.0, RT_1)
      ELSE
        Nlc_1 = RT_1
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,982296780,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 1090:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nuc_1 = LIMIT(0.0, 1.0, RT_4)
      ELSE
        Nuc_1 = RT_4
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,2112409584,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 1100:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nlb_1 = LIMIT(0.0, 1.0, RT_2)
      ELSE
        Nlb_1 = RT_2
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,844586243,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 1110:[hardlimit] Hard Limiter 

!  Hard_Limit
      IF (0.0 .LE. 1.0) THEN
        Nub_1 = LIMIT(0.0, 1.0, RT_5)
      ELSE
        Nub_1 = RT_5
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,1307634648,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 1120:[datamerge] Merges data signals into an array 

      RT_34(1) = Nua_1
      RT_34(2) = Nub_1
      RT_34(3) = Nuc_1
      RT_34(4) = Nla_1
      RT_34(5) = Nlb_1
      RT_34(6) = Nlc_1

! 1130:[Blackbox_ArmVoltage_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 790511189)
      CALL Blackbox_ArmVoltage_1Dyn(RT_38, RT_39, RT_34, Iarm_1, N, Csm)
!

! 1140:[datatap] Scalar/Array Tap 

      Vl_c_1 = RT_39(6)

! 1150:[datatap] Scalar/Array Tap 

      Vl_b_1 = RT_39(5)

! 1160:[datatap] Scalar/Array Tap 

      Vl_a_1 = RT_39(4)

! 1170:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vl_c_1
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+37),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1180:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vl_b_1
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+36),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1190:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vl_a_1
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+35),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1200:[datatap] Scalar/Array Tap 

      Vcl_c1 = RT_38(6)

! 1210:[datatap] Scalar/Array Tap 

      Vcl_b1 = RT_38(5)

! 1220:[datatap] Scalar/Array Tap 

      Vcl_a1 = RT_38(4)

! 1230:[datatap] Scalar/Array Tap 

      Vcu_c1 = RT_38(3)

! 1240:[datatap] Scalar/Array Tap 

      Vu_c_1 = RT_39(3)

! 1250:[datatap] Scalar/Array Tap 

      Vcu_b1 = RT_38(2)

! 1260:[datatap] Scalar/Array Tap 

      Vu_b_1 = RT_39(2)

! 1270:[datatap] Scalar/Array Tap 

      Vcu_a1 = RT_38(1)

! 1280:[datatap] Scalar/Array Tap 

      Vu_a_1 = RT_39(1)

! 1290:[datamerge] Merges data signals into an array 

      Vcap_l_1(1) = Vcl_a1
      Vcap_l_1(2) = Vcl_b1
      Vcap_l_1(3) = Vcl_c1

! 1300:[datamerge] Merges data signals into an array 

      Vcap_u_1(1) = Vcu_a1
      Vcap_u_1(2) = Vcu_b1
      Vcap_u_1(3) = Vcu_c1

! 1310:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vu_c_1
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+34),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1330:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vu_b_1
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+33),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3&
     &)

! 1340:[source_1] Single Phase Voltage Source Model 2 'Source1'

! Externally controlled DC source: Type: Ideal
      RVD1_1 = Vu_a_1
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS,RTCI(BRRTCI+0),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3)

! 1350:[datatap] Scalar/Array Tap 

      Ic0_1 = RT_42(3)

! 1360:[datatap] Scalar/Array Tap 

      Io0_1 = RT_31(3)

! 1:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,740687492)
      CALL E_VARRLC1_EXE(1 ,SS , RTCI(BRRTCI+10), 0, 5000.0, 0.0)
      CALL E_VARRLC1_EXE(1 ,SS , RTCI(BRRTCI+11), 0, 5000.0, 0.0)
      CALL E_VARRLC1_EXE(1 ,SS , RTCI(BRRTCI+12), 0, 5000.0, 0.0)

! 1:[varrlc] Variable R, L or C  

      CALL COMPONENT_ID(ICALL_NO,900336696)
      CALL E_VARRLC1_EXE(0 ,SS , RTCI(BRRTCI+13), 0, 5000.0, 0.0)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 31) = RT_7
      STXFRF(ISTXFRF + 43) = RT_16
      STXFRF(ISTXFRF + 66) = RT_26
      STXFRF(ISTXFRF + 67) = RT_27
      STXFRF(ISTXFRF + 111) = Iu_a_1
      STXFRF(ISTXFRF + 112) = Iu_b_1
      STXFRF(ISTXFRF + 113) = Iu_c_1
      STXFRF(ISTXFRF + 117) = Il_a_1
      STXFRF(ISTXFRF + 118) = Il_b_1
      STXFRF(ISTXFRF + 119) = Il_c_1
      STXFRF(ISTXFRF + 161) = V_dc_1
      STXFRF(ISTXFRF + 169) = Vpcc_q_pu_1
      STXFRF(ISTXFRF + 194) = Idc_1

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STXFRF(ISTXFRF + 113 + IT_0) = Iarm_u_1(IT_0)
         STXFRF(ISTXFRF + 119 + IT_0) = Iarm_l_1(IT_0)
         STXFRF(ISTXFRF + 161 + IT_0) = Vpcc_1(IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         STXFRF(ISTXFRF + 143 + IT_0) = Iarm_1(IT_0)
      END DO

!---------------------------------------
! Transfer to Exports
!---------------------------------------

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_MMC_Averaged_1Out(BR_IDX, ND_IDX, TX_IDX, SS)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_VVDC    ! 

!---------------------------------------
! Declarations 
!---------------------------------------

      INTEGER, INTENT(INOUT) :: BR_IDX, ND_IDX, TX_IDX, SS

! Control Signals
      REAL     RT_7, RT_16, RT_26, RT_27, Iu_a_1
      REAL     Iu_b_1, Iu_c_1, Iarm_u_1(3)
      REAL     Il_a_1, Il_b_1, Il_c_1
      REAL     Iarm_l_1(3), Iarm_1(6), V_dc_1
      REAL     Vpcc_1(3), Idc_1

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF, BRRTCI, NDRTCI, ITX, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 195

! Increment electrical object indices

      BRRTCI    = BR_IDX
      BR_IDX    = BR_IDX + 50
      NDRTCI    = ND_IDX
      ND_IDX    = ND_IDX + 33
      ITX       = TX_IDX
      TX_IDX    = TX_IDX + 3

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_7     = STXFRF(ISTXFRF + 31)
      RT_16    = STXFRF(ISTXFRF + 43)
      RT_26    = STXFRF(ISTXFRF + 66)
      RT_27    = STXFRF(ISTXFRF + 67)
      Iu_a_1   = STXFRF(ISTXFRF + 111)
      Iu_b_1   = STXFRF(ISTXFRF + 112)
      Iu_c_1   = STXFRF(ISTXFRF + 113)
      Il_a_1   = STXFRF(ISTXFRF + 117)
      Il_b_1   = STXFRF(ISTXFRF + 118)
      Il_c_1   = STXFRF(ISTXFRF + 119)
      V_dc_1   = STXFRF(ISTXFRF + 161)
      Idc_1    = STXFRF(ISTXFRF + 194)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Iarm_u_1(IT_0) = STXFRF(ISTXFRF + 113 + IT_0)
         Iarm_l_1(IT_0) = STXFRF(ISTXFRF + 119 + IT_0)
         Vpcc_1(IT_0) = STXFRF(ISTXFRF + 161 + IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         Iarm_1(IT_0) = STXFRF(ISTXFRF + 143 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 230:[const] Real Constant 


      RT_16 = 0.0

! 240:[const] Real Constant 


      RT_26 = 0.0

! 260:[const] Real Constant 


      RT_27 = 0.0

! 300:[ammeter] Current Meter 'Idc_1'

      Idc_1 = ( CBR(RTCI(BRRTCI+17), SS))

! 310:[ammeter] Current Meter 'Iu_a_1'

      Iu_a_1 = ( CBR(RTCI(BRRTCI+6), SS))

! 320:[const] Real Constant 


      RT_7 = 1.0

! 330:[ammeter] Current Meter 'Iu_b_1'

      Iu_b_1 = ( CBR(RTCI(BRRTCI+5), SS))

! 340:[ammeter] Current Meter 'Iu_c_1'

      Iu_c_1 = ( CBR(RTCI(BRRTCI+4), SS))

! 350:[datamerge] Merges data signals into an array 

      Iarm_u_1(1) = Iu_a_1
      Iarm_u_1(2) = Iu_b_1
      Iarm_u_1(3) = Iu_c_1

! 400:[voltmetergnd] Voltmeter (Line - Ground) 'Vpcc_1'

      Vpcc_1(1) = EMTDC_VVDC(SS, RTCI(NDRTCI+3), 0)
      Vpcc_1(2) = EMTDC_VVDC(SS, RTCI(NDRTCI+4), 0)
      Vpcc_1(3) = EMTDC_VVDC(SS, RTCI(NDRTCI+5), 0)

! 430:[voltmeter] Voltmeter (Line - Line) 'V_dc_1'

      V_dc_1 = EMTDC_VVDC(SS, RTCI(NDRTCI+2), RTCI(NDRTCI+1))

! 510:[ammeter] Current Meter 'Il_a_1'

      Il_a_1 = ( CBR(RTCI(BRRTCI+3), SS))

! 520:[ammeter] Current Meter 'Il_b_1'

      Il_b_1 = ( CBR(RTCI(BRRTCI+2), SS))

! 530:[ammeter] Current Meter 'Il_c_1'

      Il_c_1 = ( CBR(RTCI(BRRTCI+1), SS))

! 580:[datamerge] Merges data signals into an array 

      Iarm_1(1) = Iu_a_1
      Iarm_1(2) = Iu_b_1
      Iarm_1(3) = Iu_c_1
      Iarm_1(4) = Il_a_1
      Iarm_1(5) = Il_b_1
      Iarm_1(6) = Il_c_1

! 590:[Blackbox_PerUnit_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 2109480740)
      CALL Blackbox_PerUnit_2Out()
!

! 660:[Blackbox_PowerCtrl_1_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1481166677)
      CALL Blackbox_PowerCtrl_1_1_2Out()
!

! 680:[Blackbox_PLL_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1310347230)
      CALL Blackbox_PLL_2Out()
!

! 700:[Blackbox_CurrentConversion_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 1607301208)
      CALL Blackbox_CurrentConversion_1Out()
!

! 770:[Blackbox_PowerMeas_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 2045340753)
      CALL Blackbox_PowerMeas_2Out()
!

! 780:[Blackbox_PowerCtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 271340115)
      CALL Blackbox_PowerCtrl_1Out()
!

! 830:[Blackbox_PICtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 893673074)
      CALL Blackbox_PICtrl_1Out()
!

! 840:[Blackbox_PICtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 1754685605)
      CALL Blackbox_PICtrl_1Out()
!

! 1130:[Blackbox_ArmVoltage_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 790511189)
      CALL Blackbox_ArmVoltage_1Out()
!

! 1320:[datamerge] Merges data signals into an array 

      Iarm_l_1(1) = Il_a_1
      Iarm_l_1(2) = Il_b_1
      Iarm_l_1(3) = Il_c_1

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 31) = RT_7
      STXFRF(ISTXFRF + 43) = RT_16
      STXFRF(ISTXFRF + 66) = RT_26
      STXFRF(ISTXFRF + 67) = RT_27
      STXFRF(ISTXFRF + 111) = Iu_a_1
      STXFRF(ISTXFRF + 112) = Iu_b_1
      STXFRF(ISTXFRF + 113) = Iu_c_1
      STXFRF(ISTXFRF + 117) = Il_a_1
      STXFRF(ISTXFRF + 118) = Il_b_1
      STXFRF(ISTXFRF + 119) = Il_c_1
      STXFRF(ISTXFRF + 161) = V_dc_1
      STXFRF(ISTXFRF + 194) = Idc_1

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STXFRF(ISTXFRF + 113 + IT_0) = Iarm_u_1(IT_0)
         STXFRF(ISTXFRF + 119 + IT_0) = Iarm_l_1(IT_0)
         STXFRF(ISTXFRF + 161 + IT_0) = Vpcc_1(IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         STXFRF(ISTXFRF + 143 + IT_0) = Iarm_1(IT_0)
      END DO

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_MMC_Averaged_1Dyn_Begin(Larm, Rarm, Sbase,    &
     &   Vbase, KpDC, KiDC, Kpq, Kiq, Kp, Ki, Kpc, Kic, KpPLL, KiPLL,   &
     &   N, Csm, Ltrafo_pu, Rtrafo_pu, t_rst, Vtr_pri_LL_RMS,           &
     &   Vtr_sec_LL_RMS, BR_IDX, ND_IDX, TX_IDX, SS)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Larm, Rarm, Sbase
      REAL,    INTENT(IN)  :: Vbase, KpDC, KiDC
      REAL,    INTENT(IN)  :: Kpq, Kiq, Kp, Ki
      REAL,    INTENT(IN)  :: Kpc, Kic, KpPLL
      REAL,    INTENT(IN)  :: KiPLL, N, Csm
      REAL,    INTENT(IN)  :: Ltrafo_pu
      REAL,    INTENT(IN)  :: Rtrafo_pu, t_rst
      REAL,    INTENT(IN)  :: Vtr_pri_LL_RMS
      REAL,    INTENT(IN)  :: Vtr_sec_LL_RMS
      INTEGER, INTENT(INOUT) :: BR_IDX, ND_IDX, TX_IDX, SS

! Control Signals
      REAL     RT_7, RT_16, RT_26, RT_27

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4
      REAL     RVD1_5, RVD1_6

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER BRRTCI, NDRTCI, ITX, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices


! Increment electrical object indices

      BRRTCI    = BR_IDX
      BR_IDX    = BR_IDX + 50
      NDRTCI    = ND_IDX
      ND_IDX    = ND_IDX + 33
      ITX       = TX_IDX
      TX_IDX    = TX_IDX + 3

!---------------------------------------
! BlackBox generated rtc passive branch calls 
!---------------------------------------

! 1:[rtcbranch] Runtime Configurable Passive Branch
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 230:[const] Real Constant 

      RT_16 = 0.0

! 240:[const] Real Constant 

      RT_26 = 0.0

! 260:[const] Real Constant 

      RT_27 = 0.0

! 270:[div] Divider 


! 280:[datamerge] Merges data signals into an array 


! 320:[const] Real Constant 

      RT_7 = 1.0

! 360:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(3 ,SS , RTCI(BRRTCI+7), RTCI(BRRTCI+8))

! 370:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(3 ,SS , RTCI(BRRTCI+18), RTCI(BRRTCI+19))

! 380:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(3 ,SS , RTCI(BRRTCI+21), RTCI(BRRTCI+22))

! 390:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(0 ,SS , RTCI(BRRTCI+9), 0)

! 410:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(0 ,SS , RTCI(BRRTCI+20), 0)

! 420:[xfmr-3p2w] 3 Phase 2 Winding Transformer 

      CALL COMPONENT_ID(ICALL_NO,758569482)
      RVD1_1 = ONE_3RD*1000.0
      RVD1_2 = Vtr_pri_LL_RMS*SQRT_1BY3
      RVD1_3 = Vtr_sec_LL_RMS*SQRT_1BY3
      CALL E_TF2W_CFG((ITX+1),1,RVD1_1,50.0,Ltrafo_pu,Rtrafo_pu,RVD1_2,R&
     &VD1_3,2.0)
      CALL E_TF2W_CFG((ITX+2),1,RVD1_1,50.0,Ltrafo_pu,Rtrafo_pu,RVD1_2,R&
     &VD1_3,2.0)
      CALL E_TF2W_CFG((ITX+3),1,RVD1_1,50.0,Ltrafo_pu,Rtrafo_pu,RVD1_2,R&
     &VD1_3,2.0)
      IF (0.0 .LT. 1.0E-6) THEN
        RVD1_5 = 0.0
        RVD1_6 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_6 = 0.0
        RVD1_4 = 6.0/(1000.0*RVD1_6)
        RVD1_5 = RVD1_4*RVD1_2*RVD1_2
        RVD1_6 = RVD1_4*RVD1_3*RVD1_3
        IVD1_1 = 1
      ENDIF
      CALL E_BRANCH_CFG(RTCI(BRRTCI+38),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+39),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+40),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+41),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+42),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG(RTCI(BRRTCI+43),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL TSAT2_CFG(2,RTCI(BRRTCI+44),RTCI(BRRTCI+45),RTCI(BRRTCI+46),R&
     &TCI(BRRTCI+47),RTCI(BRRTCI+48),RTCI(BRRTCI+49),0,0,0,0,0,0,SS,RVD1&
     &_1,0.2,1.17,50.0,0.0,2.0,0.0,Ltrafo_pu,0.0,0.0,0.0,0.0,0.0,RVD1_2,&
     &RVD1_3,0.0,0.0)

! 440:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(0 ,SS , RTCI(BRRTCI+23), 0)

! 450:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(3 ,SS , RTCI(BRRTCI+24), RTCI(BRRTCI+25))

! 460:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(3 ,SS , RTCI(BRRTCI+27), RTCI(BRRTCI+28))

! 470:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(3 ,SS , RTCI(BRRTCI+30), RTCI(BRRTCI+31))

! 480:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(0 ,SS , RTCI(BRRTCI+26), 0)

! 490:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(0 ,SS , RTCI(BRRTCI+29), 0)

! 500:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(0 ,SS , RTCI(BRRTCI+32), 0)

! 540:[time-sig] Output of Simulation Time 


! 550:[compare] Single Input Level Comparator 


! 560:[div] Divider 


! 570:[div] Divider 


! 590:[Blackbox_PerUnit_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 2109480740)
      CALL Blackbox_PerUnit_2Dyn_Begin()
!

! 600:[gain] Gain Block 


! 610:[datatap] Scalar/Array Tap 


! 620:[datatap] Scalar/Array Tap 


! 630:[datatap] Scalar/Array Tap 


! 640:[datatap] Scalar/Array Tap 


! 650:[datatap] Scalar/Array Tap 


! 660:[Blackbox_PowerCtrl_1_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1481166677)
      CALL Blackbox_PowerCtrl_1_1_2Dyn_Begin()
!

! 670:[gain] Gain Block 


! 680:[Blackbox_PLL_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1310347230)
      CALL Blackbox_PLL_2Dyn_Begin()
!

! 690:[abcdq0] abc dq0 transformation 


! 700:[Blackbox_CurrentConversion_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 1607301208)
      CALL Blackbox_CurrentConversion_1Dyn_Begin()
!

! 710:[datatap] Scalar/Array Tap 


! 720:[datatap] Scalar/Array Tap 


! 730:[datamerge] Merges data signals into an array 


! 740:[mult] Multiplier 


! 750:[datamerge] Merges data signals into an array 


! 760:[gain] Gain Block 


! 770:[Blackbox_PowerMeas_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 2045340753)
      CALL Blackbox_PowerMeas_2Dyn_Begin()
!

! 780:[Blackbox_PowerCtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 271340115)
      CALL Blackbox_PowerCtrl_1Dyn_Begin()
!

! 790:[datatap] Scalar/Array Tap 


! 800:[datatap] Scalar/Array Tap 


! 810:[datamerge] Merges data signals into an array 


! 820:[datamerge] Merges data signals into an array 


! 830:[Blackbox_PICtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 893673074)
      CALL Blackbox_PICtrl_1Dyn_Begin()
!

! 840:[Blackbox_PICtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 1754685605)
      CALL Blackbox_PICtrl_1Dyn_Begin()
!

! 850:[mult] Multiplier 


! 860:[gain] Gain Block 


! 870:[datatap] Scalar/Array Tap 


! 880:[datatap] Scalar/Array Tap 


! 890:[datatap] Scalar/Array Tap 


! 900:[datatap] Scalar/Array Tap 


! 910:[angle_resolver] Angle Resolver 


! 920:[abcdq0] abc dq0 transformation 


! 930:[abcdq0] abc dq0 transformation 


! 940:[sumjct] Summing/Differencing Junctions 


! 950:[sumjct] Summing/Differencing Junctions 


! 960:[sumjct] Summing/Differencing Junctions 


! 970:[sumjct] Summing/Differencing Junctions 


! 980:[sumjct] Summing/Differencing Junctions 


! 990:[sumjct] Summing/Differencing Junctions 


! 1000:[gain] Gain Block 


! 1010:[gain] Gain Block 


! 1020:[gain] Gain Block 


! 1030:[gain] Gain Block 


! 1040:[gain] Gain Block 


! 1050:[gain] Gain Block 


! 1060:[hardlimit] Hard Limiter 


! 1070:[hardlimit] Hard Limiter 


! 1080:[hardlimit] Hard Limiter 


! 1090:[hardlimit] Hard Limiter 


! 1100:[hardlimit] Hard Limiter 


! 1110:[hardlimit] Hard Limiter 


! 1120:[datamerge] Merges data signals into an array 


! 1130:[Blackbox_ArmVoltage_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 790511189)
      CALL Blackbox_ArmVoltage_1Dyn_Begin()
!

! 1140:[datatap] Scalar/Array Tap 


! 1150:[datatap] Scalar/Array Tap 


! 1160:[datatap] Scalar/Array Tap 


! 1170:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1180:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1190:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1200:[datatap] Scalar/Array Tap 


! 1210:[datatap] Scalar/Array Tap 


! 1220:[datatap] Scalar/Array Tap 


! 1230:[datatap] Scalar/Array Tap 


! 1240:[datatap] Scalar/Array Tap 


! 1250:[datatap] Scalar/Array Tap 


! 1260:[datatap] Scalar/Array Tap 


! 1270:[datatap] Scalar/Array Tap 


! 1280:[datatap] Scalar/Array Tap 


! 1290:[datamerge] Merges data signals into an array 


! 1300:[datamerge] Merges data signals into an array 


! 1310:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1330:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1340:[source_1] Single Phase Voltage Source Model 2 'Source1'

      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.0
      NRTCF = NRTCF + 2

! 1350:[datatap] Scalar/Array Tap 


! 1360:[datatap] Scalar/Array Tap 


! 1:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(1 ,SS , RTCI(BRRTCI+10), 0)
      CALL E_VARRLC1_CFG(1 ,SS , RTCI(BRRTCI+11), 0)
      CALL E_VARRLC1_CFG(1 ,SS , RTCI(BRRTCI+12), 0)

! 1:[varrlc] Variable R, L or C  

      CALL E_VARRLC1_CFG(0 ,SS , RTCI(BRRTCI+13), 0)

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_MMC_Averaged_1Out_Begin(Larm, Rarm, Sbase,    &
     &   Vbase, KpDC, KiDC, Kpq, Kiq, Kp, Ki, Kpc, Kic, KpPLL, KiPLL,   &
     &   N, Csm, Ltrafo_pu, Rtrafo_pu, t_rst, Vtr_pri_LL_RMS,           &
     &   Vtr_sec_LL_RMS, BR_IDX, ND_IDX, TX_IDX, SS)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Larm, Rarm, Sbase
      REAL,    INTENT(IN)  :: Vbase, KpDC, KiDC
      REAL,    INTENT(IN)  :: Kpq, Kiq, Kp, Ki
      REAL,    INTENT(IN)  :: Kpc, Kic, KpPLL
      REAL,    INTENT(IN)  :: KiPLL, N, Csm
      REAL,    INTENT(IN)  :: Ltrafo_pu
      REAL,    INTENT(IN)  :: Rtrafo_pu, t_rst
      REAL,    INTENT(IN)  :: Vtr_pri_LL_RMS
      REAL,    INTENT(IN)  :: Vtr_sec_LL_RMS
      INTEGER, INTENT(INOUT) :: BR_IDX, ND_IDX, TX_IDX, SS

! Control Signals
      REAL     RT_7, RT_16, RT_26, RT_27

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER BRRTCI, NDRTCI, ITX, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices


! Increment electrical object indices

      BRRTCI    = BR_IDX
      BR_IDX    = BR_IDX + 50
      NDRTCI    = ND_IDX
      ND_IDX    = ND_IDX + 33
      ITX       = TX_IDX
      TX_IDX    = TX_IDX + 3

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 230:[const] Real Constant 

      RT_16 = 0.0

! 240:[const] Real Constant 

      RT_26 = 0.0

! 260:[const] Real Constant 

      RT_27 = 0.0

! 320:[const] Real Constant 

      RT_7 = 1.0

! 350:[datamerge] Merges data signals into an array 


! 580:[datamerge] Merges data signals into an array 


! 590:[Blackbox_PerUnit_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 2109480740)
      CALL Blackbox_PerUnit_2Out_Begin()
!

! 660:[Blackbox_PowerCtrl_1_1_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1481166677)
      CALL Blackbox_PowerCtrl_1_1_2Out_Begin()
!

! 680:[Blackbox_PLL_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 1310347230)
      CALL Blackbox_PLL_2Out_Begin()
!

! 700:[Blackbox_CurrentConversion_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 1607301208)
      CALL Blackbox_CurrentConversion_1Out_Begin()
!

! 770:[Blackbox_PowerMeas_2]  

!
      CALL COMPONENT_ID(ICALL_NO, 2045340753)
      CALL Blackbox_PowerMeas_2Out_Begin()
!

! 780:[Blackbox_PowerCtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 271340115)
      CALL Blackbox_PowerCtrl_1Out_Begin()
!

! 830:[Blackbox_PICtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 893673074)
      CALL Blackbox_PICtrl_1Out_Begin()
!

! 840:[Blackbox_PICtrl_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 1754685605)
      CALL Blackbox_PICtrl_1Out_Begin()
!

! 1130:[Blackbox_ArmVoltage_1]  

!
      CALL COMPONENT_ID(ICALL_NO, 790511189)
      CALL Blackbox_ArmVoltage_1Out_Begin()
!

! 1320:[datamerge] Merges data signals into an array 


      RETURN
      END

