!=======================================================================
! Generated by: BlackBox Using PSCAD v5.0.0.0
!-----------------------------------------------------------------------
! Component     : ArmVoltage_1
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Blackbox_ArmVoltage_1Dyn(VSM, Varm, NumSM, Iarm, N,    &
     &   Csm)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: NumSM(6), Iarm(6)
      REAL,    INTENT(IN)  :: N, Csm
      REAL,    INTENT(OUT) :: VSM(6), Varm(6)

! Control Signals
      REAL     RT_1, RT_2, Iua, RT_3, RT_4, RT_5
      REAL     RT_6, Ila, Vua, Vla, Vlb, Vub
      REAL     RT_7, Ilb, RT_8, RT_9, RT_10
      REAL     RT_11, RT_12, Iub, Vlc, Vuc, RT_13
      REAL     Ilc, RT_14, RT_15, RT_16, RT_17
      REAL     RT_18, Iuc, Vcua, Vcub, Vcuc, Vcla
      REAL     Vclb, Vclc, Nlc, Nlb, Nla, Nuc
      REAL     Nub, Nua

! Internal Variables
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 68
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 

      Iua = Iarm(1)

! 30:[datatap] Scalar/Array Tap 

      Iub = Iarm(2)

! 40:[datatap] Scalar/Array Tap 

      Iuc = Iarm(3)

! 50:[datatap] Scalar/Array Tap 

      Ila = Iarm(4)

! 60:[datatap] Scalar/Array Tap 

      Ilb = Iarm(5)

! 70:[datatap] Scalar/Array Tap 

      Ilc = Iarm(6)

! 110:[datatap] Scalar/Array Tap 

      Nua = NumSM(1)

! 120:[datatap] Scalar/Array Tap 

      Nub = NumSM(2)

! 130:[mult] Multiplier 

      RT_12 = Nub * Iub

! 140:[gain] Gain Block 

!  Gain
      RT_11 = N * RT_12

! 150:[div] Divider 

      IF (ABS(Csm) .LT. 1.0E-100) THEN
         IF (Csm .LT. 0.0)  THEN
            RT_10 = -1.0E100 * RT_11
         ELSE
            RT_10 =  1.0E100 * RT_11
         ENDIF
      ELSE
         RT_10 = RT_11 / Csm
      ENDIF

! 160:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_10
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      Vcub = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, 0.0, 1000000000.0, RV&
     &D2_2, RVD2_1)

! 170:[datatap] Scalar/Array Tap 

      Nuc = NumSM(3)

! 180:[mult] Multiplier 

      Vub = Vcub * Nub

! 190:[datatap] Scalar/Array Tap 

      Nla = NumSM(4)

! 200:[datatap] Scalar/Array Tap 

      Nlb = NumSM(5)

! 210:[datatap] Scalar/Array Tap 

      Nlc = NumSM(6)

! 220:[mult] Multiplier 

      RT_18 = Nuc * Iuc

! 230:[gain] Gain Block 

!  Gain
      RT_17 = N * RT_18

! 240:[div] Divider 

      IF (ABS(Csm) .LT. 1.0E-100) THEN
         IF (Csm .LT. 0.0)  THEN
            RT_16 = -1.0E100 * RT_17
         ELSE
            RT_16 =  1.0E100 * RT_17
         ENDIF
      ELSE
         RT_16 = RT_17 / Csm
      ENDIF

! 250:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_16
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      Vcuc = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, 0.0, 1000000000.0, RV&
     &D2_2, RVD2_1)

! 260:[mult] Multiplier 

      Vuc = Vcuc * Nuc

! 270:[mult] Multiplier 

      RT_13 = Nlc * Ilc

! 280:[gain] Gain Block 

!  Gain
      RT_15 = N * RT_13

! 290:[div] Divider 

      IF (ABS(Csm) .LT. 1.0E-100) THEN
         IF (Csm .LT. 0.0)  THEN
            RT_14 = -1.0E100 * RT_15
         ELSE
            RT_14 =  1.0E100 * RT_15
         ENDIF
      ELSE
         RT_14 = RT_15 / Csm
      ENDIF

! 300:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_14
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      Vclc = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, 0.0, 1000000000.0, RV&
     &D2_2, RVD2_1)

! 310:[mult] Multiplier 

      Vlc = Vclc * Nlc

! 320:[mult] Multiplier 

      RT_2 = Nua * Iua

! 330:[gain] Gain Block 

!  Gain
      RT_3 = N * RT_2

! 340:[div] Divider 

      IF (ABS(Csm) .LT. 1.0E-100) THEN
         IF (Csm .LT. 0.0)  THEN
            RT_1 = -1.0E100 * RT_3
         ELSE
            RT_1 =  1.0E100 * RT_3
         ENDIF
      ELSE
         RT_1 = RT_3 / Csm
      ENDIF

! 350:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_1
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      Vcua = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, 0.0, 1000000000.0, RV&
     &D2_2, RVD2_1)

! 360:[mult] Multiplier 

      Vua = Vcua * Nua

! 370:[mult] Multiplier 

      RT_6 = Nla * Ila

! 380:[gain] Gain Block 

!  Gain
      RT_5 = N * RT_6

! 390:[div] Divider 

      IF (ABS(Csm) .LT. 1.0E-100) THEN
         IF (Csm .LT. 0.0)  THEN
            RT_4 = -1.0E100 * RT_5
         ELSE
            RT_4 =  1.0E100 * RT_5
         ENDIF
      ELSE
         RT_4 = RT_5 / Csm
      ENDIF

! 400:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_4
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      Vcla = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, 0.0, 1000000000.0, RV&
     &D2_2, RVD2_1)

! 410:[mult] Multiplier 

      Vla = Vcla * Nla

! 420:[mult] Multiplier 

      RT_7 = Nlb * Ilb

! 430:[gain] Gain Block 

!  Gain
      RT_9 = N * RT_7

! 440:[div] Divider 

      IF (ABS(Csm) .LT. 1.0E-100) THEN
         IF (Csm .LT. 0.0)  THEN
            RT_8 = -1.0E100 * RT_9
         ELSE
            RT_8 =  1.0E100 * RT_9
         ENDIF
      ELSE
         RT_8 = RT_9 / Csm
      ENDIF

! 450:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_8
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      Vclb = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, 0.0, 1000000000.0, RV&
     &D2_2, RVD2_1)

! 460:[mult] Multiplier 

      Vlb = Vclb * Nlb

! 470:[datamerge] Merges data signals into an array 

      VSM(1) = Vcua
      VSM(2) = Vcub
      VSM(3) = Vcuc
      VSM(4) = Vcla
      VSM(5) = Vclb
      VSM(6) = Vclc

! 480:[datamerge] Merges data signals into an array 

      Varm(1) = Vua
      Varm(2) = Vub
      Varm(3) = Vuc
      Varm(4) = Vla
      Varm(5) = Vlb
      Varm(6) = Vlc

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !VSM      is output
      !Varm     is output

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_ArmVoltage_1Out()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 68
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_ArmVoltage_1Dyn_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! BlackBox generated rtc passive branch calls 
!---------------------------------------

! 1:[rtcbranch] Runtime Configurable Passive Branch
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 


! 30:[datatap] Scalar/Array Tap 


! 40:[datatap] Scalar/Array Tap 


! 50:[datatap] Scalar/Array Tap 


! 60:[datatap] Scalar/Array Tap 


! 70:[datatap] Scalar/Array Tap 


! 110:[datatap] Scalar/Array Tap 


! 120:[datatap] Scalar/Array Tap 


! 130:[mult] Multiplier 


! 140:[gain] Gain Block 


! 150:[div] Divider 


! 160:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 640.0
      NRTCF = NRTCF + 1

! 170:[datatap] Scalar/Array Tap 


! 180:[mult] Multiplier 


! 190:[datatap] Scalar/Array Tap 


! 200:[datatap] Scalar/Array Tap 


! 210:[datatap] Scalar/Array Tap 


! 220:[mult] Multiplier 


! 230:[gain] Gain Block 


! 240:[div] Divider 


! 250:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 640.0
      NRTCF = NRTCF + 1

! 260:[mult] Multiplier 


! 270:[mult] Multiplier 


! 280:[gain] Gain Block 


! 290:[div] Divider 


! 300:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 640.0
      NRTCF = NRTCF + 1

! 310:[mult] Multiplier 


! 320:[mult] Multiplier 


! 330:[gain] Gain Block 


! 340:[div] Divider 


! 350:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 640.0
      NRTCF = NRTCF + 1

! 360:[mult] Multiplier 


! 370:[mult] Multiplier 


! 380:[gain] Gain Block 


! 390:[div] Divider 


! 400:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 640.0
      NRTCF = NRTCF + 1

! 410:[mult] Multiplier 


! 420:[mult] Multiplier 


! 430:[gain] Gain Block 


! 440:[div] Divider 


! 450:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 640.0
      NRTCF = NRTCF + 1

! 460:[mult] Multiplier 


! 470:[datamerge] Merges data signals into an array 


! 480:[datamerge] Merges data signals into an array 


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_ArmVoltage_1Out_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


      RETURN
      END

