!=======================================================================
! Generated by: BlackBox Using PSCAD v5.0.0.0
!-----------------------------------------------------------------------
! Component     : PICtrl_1
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Blackbox_PICtrl_1Dyn(n_dq, V_dc, wl, Idq_meas,         &
     &   Idq_ref, Vdq_ff, Kp, Ki, t_rst)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: V_dc, wl
      REAL,    INTENT(IN)  :: Idq_meas(2)
      REAL,    INTENT(IN)  :: Idq_ref(2)
      REAL,    INTENT(IN)  :: Vdq_ff(2), Kp, Ki
      REAL,    INTENT(IN)  :: t_rst
      REAL,    INTENT(OUT) :: n_dq(2)

! Control Signals
      INTEGER  IT_1, IT_2
      REAL     RT_1, RT_2, RT_3, RT_4, Vd_ff
      REAL     RT_5, Iodref, RT_6, n_d, RT_7
      REAL     Ioqref, Ioq, RT_8, Vq_ff, RT_9
      REAL     RT_10, RT_11, Iod, RT_12, n_q
      REAL     RT_13, RT_14, RT_15, RT_16, RT_17
      REAL     RT_18, RT_19, Rst, RT_20, Ti

! Internal Variables
      REAL     RVD2_1(2), RVD1_1, RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRI, ISTXFRF, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRI   = NSTXFRI
      NSTXFRI   = NSTXFRI + 2
      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 43
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_20    = STXFRF(ISTXFRF + 41)

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 60:[gain] Gain Block 

!  Gain
      RT_1 = 0.5 * V_dc

! 70:[datatap] Scalar/Array Tap 

      Iodref = Idq_ref(1)

! 80:[datatap] Scalar/Array Tap 

      Ioqref = Idq_ref(2)

! 90:[time-sig] Output of Simulation Time 

      RT_7 = TIME

! 100:[compare] Single Input Level Comparator 

!
!
      CALL EMTDC_X2COMP(0,0,t_rst,RT_7,1.0,0.0,0.0,RVD2_1)
      Rst = RVD2_1(1)

! 110:[inv] Interpolated Logic Inverter 

      IF (NINT(Rst) .NE. 0) THEN
         IT_1 = 0
      ELSE
         IT_1 = 1
      ENDIF

! 130:[datatap] Scalar/Array Tap 

      Iod = Idq_meas(1)

! 140:[datatap] Scalar/Array Tap 

      Ioq = Idq_meas(2)

! 160:[datatap] Scalar/Array Tap 

      Vd_ff = Vdq_ff(1)

! 170:[mult] Multiplier 

      RT_10 = Iod * wl

! 180:[gain] Gain Block 

!  Gain
      RT_13 = 0.5 * V_dc

! 190:[datatap] Scalar/Array Tap 

      Vq_ff = Vdq_ff(2)

! 200:[const] Real Constant 

      RT_20 = 1.0

! 220:[inv] Interpolated Logic Inverter 

      IF (NINT(Rst) .NE. 0) THEN
         IT_2 = 0
      ELSE
         IT_2 = 1
      ENDIF

! 230:[sumjct] Summing/Differencing Junctions 

      RT_6 = + Iodref - Iod

! 240:[mult] Multiplier 

      RT_19 = RT_6 * REAL(IT_2)

! 250:[gain] Gain Block 

!  Gain
      RT_17 = Kp * RT_19

! 260:[mult] Multiplier 

      RT_4 = Ioq * wl

! 270:[sumjct] Summing/Differencing Junctions 

      RT_8 = + Ioqref - Ioq

! 280:[mult] Multiplier 

      RT_16 = RT_8 * REAL(IT_1)

! 290:[gain] Gain Block 

!  Gain
      RT_14 = Kp * RT_16

! 300:[div] Divider 

      IF (ABS(Ki) .LT. 1.0E-100) THEN
         IF (Ki .LT. 0.0)  THEN
            Ti = -1.0E100 * RT_20
         ELSE
            Ti =  1.0E100 * RT_20
         ENDIF
      ELSE
         Ti = RT_20 / Ki
      ENDIF

! 310:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_19
      RVD2_1(2) = 0.0
      RVD2_2(1) = FLOAT(NINT(Rst))
      RVD2_2(2) = 0.0
      RT_18 = EMTDC_XINT(0, 0, 1, RVD1_1, Ti, 0.0, -1000000000.0, 100000&
     &0000.0, RVD2_2, RVD2_1)

! 320:[integral] Interpolated Integrator 

      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_16
      RVD2_1(2) = 0.0
      RVD2_2(1) = FLOAT(NINT(Rst))
      RVD2_2(2) = 0.0
      RT_15 = EMTDC_XINT(0, 0, 1, RVD1_1, Ti, 0.0, -1000000000.0, 100000&
     &0000.0, RVD2_2, RVD2_1)

! 330:[sumjct] Summing/Differencing Junctions 

      RT_5 = + RT_17 + RT_18

! 340:[sumjct] Summing/Differencing Junctions 

      RT_3 = + Vd_ff + RT_5 + RT_4

! 350:[sumjct] Summing/Differencing Junctions 

      RT_9 = + RT_14 + RT_15

! 360:[sumjct] Summing/Differencing Junctions 

      RT_11 = + Vq_ff + RT_9 - RT_10

! 370:[gain] Gain Block 

!  Gain
      RT_2 = -1.0 * RT_3

! 380:[gain] Gain Block 

!  Gain
      RT_12 = -1.0 * RT_11

! 390:[div] Divider 

      IF (ABS(RT_1) .LT. 1.0E-100) THEN
         IF (RT_1 .LT. 0.0)  THEN
            n_d = -1.0E100 * RT_2
         ELSE
            n_d =  1.0E100 * RT_2
         ENDIF
      ELSE
         n_d = RT_2 / RT_1
      ENDIF

! 400:[div] Divider 

      IF (ABS(RT_13) .LT. 1.0E-100) THEN
         IF (RT_13 .LT. 0.0)  THEN
            n_q = -1.0E100 * RT_12
         ELSE
            n_q =  1.0E100 * RT_12
         ENDIF
      ELSE
         n_q = RT_12 / RT_13
      ENDIF

! 410:[datamerge] Merges data signals into an array 

      n_dq(1) = n_d
      n_dq(2) = n_q

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 41) = RT_20

!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !n_dq     is output

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PICtrl_1Out()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Control Signals
      REAL     RT_20

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRI, ISTXFRF

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRI   = NSTXFRI
      NSTXFRI   = NSTXFRI + 2
      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 43
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_20    = STXFRF(ISTXFRF + 41)

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 200:[const] Real Constant 


      RT_20 = 1.0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 41) = RT_20

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PICtrl_1Dyn_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals
      REAL     RT_20

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! BlackBox generated rtc passive branch calls 
!---------------------------------------

! 1:[rtcbranch] Runtime Configurable Passive Branch
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 60:[gain] Gain Block 


! 70:[datatap] Scalar/Array Tap 


! 80:[datatap] Scalar/Array Tap 


! 90:[time-sig] Output of Simulation Time 


! 100:[compare] Single Input Level Comparator 


! 110:[inv] Interpolated Logic Inverter 


! 130:[datatap] Scalar/Array Tap 


! 140:[datatap] Scalar/Array Tap 


! 160:[datatap] Scalar/Array Tap 


! 170:[mult] Multiplier 


! 180:[gain] Gain Block 


! 190:[datatap] Scalar/Array Tap 


! 200:[const] Real Constant 

      RT_20 = 1.0

! 220:[inv] Interpolated Logic Inverter 


! 230:[sumjct] Summing/Differencing Junctions 


! 240:[mult] Multiplier 


! 250:[gain] Gain Block 


! 260:[mult] Multiplier 


! 270:[sumjct] Summing/Differencing Junctions 


! 280:[mult] Multiplier 


! 290:[gain] Gain Block 


! 300:[div] Divider 


! 310:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 320:[integral] Interpolated Integrator 

      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 330:[sumjct] Summing/Differencing Junctions 


! 340:[sumjct] Summing/Differencing Junctions 


! 350:[sumjct] Summing/Differencing Junctions 


! 360:[sumjct] Summing/Differencing Junctions 


! 370:[gain] Gain Block 


! 380:[gain] Gain Block 


! 390:[div] Divider 


! 400:[div] Divider 


! 410:[datamerge] Merges data signals into an array 


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PICtrl_1Out_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals
      REAL     RT_20

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 200:[const] Real Constant 

      RT_20 = 1.0

      RETURN
      END

