!=======================================================================
! Generated by: BlackBox Using PSCAD v5.0.0.0
!-----------------------------------------------------------------------
! Component     : PerUnit_2
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Blackbox_PerUnit_2Dyn(wL_pu, V_dc_pu, V_MMC_pu,        &
     &   Iarm_pu, V_dc, V_MMC, Iarm, baseConv_v, baseConv_i, Ltrafo_pu, &
     &   Vbase_dc, Sbase, Larm, Vbase)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: V_dc, V_MMC(3)
      REAL,    INTENT(IN)  :: Iarm(6), Ltrafo_pu
      REAL,    INTENT(IN)  :: Vbase_dc, Sbase
      REAL,    INTENT(IN)  :: Larm, Vbase
      REAL,    INTENT(OUT) :: wL_pu(2), V_dc_pu
      REAL,    INTENT(OUT) :: V_MMC_pu(3)
      REAL,    INTENT(OUT) :: Iarm_pu(6)
      REAL,    INTENT(OUT) :: baseConv_v
      REAL,    INTENT(OUT) :: baseConv_i

! Control Signals
      REAL     RT_1, Lbase_dc, Zbase_dc, Lbase_ac
      REAL     Zbase_ac, RT_2, RT_3, RT_4, wLeq
      REAL     RT_5, RT_6, RT_7, Ltrafo, RT_8, wg
      REAL     RT_9, RT_10, RT_11, w2La, RT_12
      REAL     RT_13, RT_14, RT_15, Vbase_LN_PK
      REAL     Ibase_ac, Ibase_dc

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 55
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_6     = STXFRF(ISTXFRF + 39)
      RT_7     = STXFRF(ISTXFRF + 40)
      RT_11    = STXFRF(ISTXFRF + 46)
      RT_13    = STXFRF(ISTXFRF + 49)
      RT_14    = STXFRF(ISTXFRF + 50)

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[emtconst] Commonly Used Constants (pi...) 

      RT_13 = SQRT_2

! 50:[emtconst] Commonly Used Constants (pi...) 

      RT_14 = SQRT_3

! 110:[div] Divider 

      IF (ABS(Vbase_dc) .LT. 1.0E-100) THEN
         IF (Vbase_dc .LT. 0.0)  THEN
            Ibase_dc = -1.0E100 * Sbase
         ELSE
            Ibase_dc =  1.0E100 * Sbase
         ENDIF
      ELSE
         Ibase_dc = Sbase / Vbase_dc
      ENDIF

! 120:[square] Square 

      RT_10 = Vbase * Vbase

! 130:[const] Real Constant 

      RT_11 = 1000.0

! 140:[emtconst] Commonly Used Constants (pi...) 

      RT_6 = TWO_PI

! 150:[const] Real Constant 

      RT_7 = 50.0

! 160:[gain] Gain Block 

!  Gain
      RT_4 = 0.5 * Larm

! 170:[gain] Gain Block 

!  Gain
      RT_12 = 2.0 * Larm

! 180:[div] Divider 

      IF (ABS(Vbase_dc) .LT. 1.0E-100) THEN
         IF (Vbase_dc .LT. 0.0)  THEN
            V_dc_pu = -1.0E100 * V_dc
         ELSE
            V_dc_pu =  1.0E100 * V_dc
         ENDIF
      ELSE
         V_dc_pu = V_dc / Vbase_dc
      ENDIF

! 190:[div] Divider 

      IF (ABS(RT_14) .LT. 1.0E-100) THEN
         IF (RT_14 .LT. 0.0)  THEN
            RT_15 = -1.0E100 * RT_13
         ELSE
            RT_15 =  1.0E100 * RT_13
         ENDIF
      ELSE
         RT_15 = RT_13 / RT_14
      ENDIF

! 200:[div] Divider 

      IF (ABS(Ibase_dc) .LT. 1.0E-100) THEN
         IF (Ibase_dc .LT. 0.0)  THEN
            Zbase_dc = -1.0E100 * Vbase_dc
         ELSE
            Zbase_dc =  1.0E100 * Vbase_dc
         ENDIF
      ELSE
         Zbase_dc = Vbase_dc / Ibase_dc
      ENDIF

! 210:[div] Divider 

      IF (ABS(RT_11) .LT. 1.0E-100) THEN
         IF (RT_11 .LT. 0.0)  THEN
            RT_9 = -1.0E100 * RT_10
         ELSE
            RT_9 =  1.0E100 * RT_10
         ENDIF
      ELSE
         RT_9 = RT_10 / RT_11
      ENDIF

! 220:[mult] Multiplier 

      RT_8 = RT_9 * Ltrafo_pu

! 230:[mult] Multiplier 

      wg = RT_6 * RT_7

! 240:[mult] Multiplier 

      w2La = RT_12 * wg

! 250:[div] Divider 

      IF (ABS(Zbase_dc) .LT. 1.0E-100) THEN
         IF (Zbase_dc .LT. 0.0)  THEN
            RT_3 = -1.0E100 * w2La
         ELSE
            RT_3 =  1.0E100 * w2La
         ENDIF
      ELSE
         RT_3 = w2La / Zbase_dc
      ENDIF

! 260:[mult] Multiplier 

      Vbase_LN_PK = Vbase * RT_15

! 270:[gain] Gain Block 

!  Gain
      RT_1 = 1.5 * Vbase_LN_PK

! 280:[div] Divider 

      IF (ABS(wg) .LT. 1.0E-100) THEN
         IF (wg .LT. 0.0)  THEN
            Ltrafo = -1.0E100 * RT_8
         ELSE
            Ltrafo =  1.0E100 * RT_8
         ENDIF
      ELSE
         Ltrafo = RT_8 / wg
      ENDIF

! 290:[sumjct] Summing/Differencing Junctions 

      RT_5 = + RT_4 + Ltrafo

! 300:[mult] Multiplier 

      wLeq = RT_5 * wg

! 310:[div] Divider 

      IF (ABS(RT_1) .LT. 1.0E-100) THEN
         IF (RT_1 .LT. 0.0)  THEN
            Ibase_ac = -1.0E100 * Sbase
         ELSE
            Ibase_ac =  1.0E100 * Sbase
         ENDIF
      ELSE
         Ibase_ac = Sbase / RT_1
      ENDIF

! 320:[div] Divider 

      IF (ABS(Ibase_ac) .LT. 1.0E-100) THEN
         IF (Ibase_ac .LT. 0.0)  THEN
            Zbase_ac = -1.0E100 * Vbase_LN_PK
         ELSE
            Zbase_ac =  1.0E100 * Vbase_LN_PK
         ENDIF
      ELSE
         Zbase_ac = Vbase_LN_PK / Ibase_ac
      ENDIF

! 330:[div] Divider 

      IF (ABS(Zbase_ac) .LT. 1.0E-100) THEN
         IF (Zbase_ac .LT. 0.0)  THEN
            RT_2 = -1.0E100 * wLeq
         ELSE
            RT_2 =  1.0E100 * wLeq
         ENDIF
      ELSE
         RT_2 = wLeq / Zbase_ac
      ENDIF

! 340:[div] Divider 

      IF (ABS(Ibase_dc) .LT. 1.0E-100) THEN
         IF (Ibase_dc .LT. 0.0)  THEN
            baseConv_i = -1.0E100 * Ibase_ac
         ELSE
            baseConv_i =  1.0E100 * Ibase_ac
         ENDIF
      ELSE
         baseConv_i = Ibase_ac / Ibase_dc
      ENDIF

! 350:[div] Divider 

      IF (ABS(Vbase_dc) .LT. 1.0E-100) THEN
         IF (Vbase_dc .LT. 0.0)  THEN
            baseConv_v = -1.0E100 * Vbase_LN_PK
         ELSE
            baseConv_v =  1.0E100 * Vbase_LN_PK
         ENDIF
      ELSE
         baseConv_v = Vbase_LN_PK / Vbase_dc
      ENDIF

! 360:[div] Divider 

      IF (ABS(Ibase_ac) .LT. 1.0E-100) THEN
         IF (Ibase_ac .LT. 0.0)  THEN
            Iarm_pu = -1.0E100 * Iarm
         ELSE
            Iarm_pu =  1.0E100 * Iarm
         ENDIF
      ELSE
         Iarm_pu = Iarm / Ibase_ac
      ENDIF

! 370:[div] Divider 

      IF (ABS(Vbase_LN_PK) .LT. 1.0E-100) THEN
         IF (Vbase_LN_PK .LT. 0.0)  THEN
            V_MMC_pu = -1.0E100 * V_MMC
         ELSE
            V_MMC_pu =  1.0E100 * V_MMC
         ENDIF
      ELSE
         V_MMC_pu = V_MMC / Vbase_LN_PK
      ENDIF

! 380:[datamerge] Merges data signals into an array 

      wL_pu(1) = RT_2
      wL_pu(2) = RT_3

! 410:[div] Divider 

      IF (ABS(wg) .LT. 1.0E-100) THEN
         IF (wg .LT. 0.0)  THEN
            Lbase_dc = -1.0E100 * Zbase_dc
         ELSE
            Lbase_dc =  1.0E100 * Zbase_dc
         ENDIF
      ELSE
         Lbase_dc = Zbase_dc / wg
      ENDIF

! 440:[div] Divider 

      IF (ABS(wg) .LT. 1.0E-100) THEN
         IF (wg .LT. 0.0)  THEN
            Lbase_ac = -1.0E100 * Zbase_ac
         ELSE
            Lbase_ac =  1.0E100 * Zbase_ac
         ENDIF
      ELSE
         Lbase_ac = Zbase_ac / wg
      ENDIF

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 39) = RT_6
      STXFRF(ISTXFRF + 40) = RT_7
      STXFRF(ISTXFRF + 46) = RT_11
      STXFRF(ISTXFRF + 49) = RT_13
      STXFRF(ISTXFRF + 50) = RT_14

!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !wL_pu    is output
      !V_dc_pu  is output
      !V_MMC_pu is output
      !Iarm_pu  is output
      !baseConv_v is output
      !baseConv_i is output

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PerUnit_2Out()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Declarations 
!---------------------------------------


! Control Signals
      REAL     RT_6, RT_7, RT_11, RT_13, RT_14

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 55
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_6     = STXFRF(ISTXFRF + 39)
      RT_7     = STXFRF(ISTXFRF + 40)
      RT_11    = STXFRF(ISTXFRF + 46)
      RT_13    = STXFRF(ISTXFRF + 49)
      RT_14    = STXFRF(ISTXFRF + 50)

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[emtconst] Commonly Used Constants (pi...) 

      RT_13 = SQRT_2

! 50:[emtconst] Commonly Used Constants (pi...) 

      RT_14 = SQRT_3

! 130:[const] Real Constant 


      RT_11 = 1000.0

! 140:[emtconst] Commonly Used Constants (pi...) 

      RT_6 = TWO_PI

! 150:[const] Real Constant 


      RT_7 = 50.0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STXFRF(ISTXFRF + 39) = RT_6
      STXFRF(ISTXFRF + 40) = RT_7
      STXFRF(ISTXFRF + 46) = RT_11
      STXFRF(ISTXFRF + 49) = RT_13
      STXFRF(ISTXFRF + 50) = RT_14

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PerUnit_2Dyn_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals
      REAL     RT_6, RT_7, RT_11, RT_13, RT_14

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! BlackBox generated rtc passive branch calls 
!---------------------------------------

! 1:[rtcbranch] Runtime Configurable Passive Branch
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[emtconst] Commonly Used Constants (pi...) 

      RT_13 = SQRT_2

! 50:[emtconst] Commonly Used Constants (pi...) 

      RT_14 = SQRT_3

! 110:[div] Divider 


! 120:[square] Square 


! 130:[const] Real Constant 

      RT_11 = 1000.0

! 140:[emtconst] Commonly Used Constants (pi...) 

      RT_6 = TWO_PI

! 150:[const] Real Constant 

      RT_7 = 50.0

! 160:[gain] Gain Block 


! 170:[gain] Gain Block 


! 180:[div] Divider 


! 190:[div] Divider 


! 200:[div] Divider 


! 210:[div] Divider 


! 220:[mult] Multiplier 


! 230:[mult] Multiplier 


! 240:[mult] Multiplier 


! 250:[div] Divider 


! 260:[mult] Multiplier 


! 270:[gain] Gain Block 


! 280:[div] Divider 


! 290:[sumjct] Summing/Differencing Junctions 


! 300:[mult] Multiplier 


! 310:[div] Divider 


! 320:[div] Divider 


! 330:[div] Divider 


! 340:[div] Divider 


! 350:[div] Divider 


! 360:[div] Divider 


! 370:[div] Divider 


! 380:[datamerge] Merges data signals into an array 


! 410:[div] Divider 


! 440:[div] Divider 


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PerUnit_2Out_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals
      REAL     RT_6, RT_7, RT_11, RT_13, RT_14

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[emtconst] Commonly Used Constants (pi...) 

      RT_13 = SQRT_2

! 50:[emtconst] Commonly Used Constants (pi...) 

      RT_14 = SQRT_3

! 130:[const] Real Constant 

      RT_11 = 1000.0

! 140:[emtconst] Commonly Used Constants (pi...) 

      RT_6 = TWO_PI

! 150:[const] Real Constant 

      RT_7 = 50.0

      RETURN
      END

