!=======================================================================
! Generated by: BlackBox Using PSCAD v5.0.0.0
!-----------------------------------------------------------------------
! Component     : PowerMeas_2
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Blackbox_PowerMeas_2Dyn(Q, P, I, V)

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: I(2), V(2)
      REAL,    INTENT(OUT) :: Q, P

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, Ioq, Iod
      REAL     Vod, Voq

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF, IT_0

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 14
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 

      Vod = V(1)

! 30:[datatap] Scalar/Array Tap 

      Voq = V(2)

! 50:[datatap] Scalar/Array Tap 

      Iod = I(1)

! 60:[datatap] Scalar/Array Tap 

      Ioq = I(2)

! 70:[mult] Multiplier 

      RT_3 = Voq * Ioq

! 80:[mult] Multiplier 

      RT_4 = Voq * Iod

! 90:[mult] Multiplier 

      RT_1 = Vod * Ioq

! 100:[mult] Multiplier 

      RT_2 = Vod * Iod

! 110:[sumjct] Summing/Differencing Junctions 

      P = + RT_2 + RT_3

! 120:[sumjct] Summing/Differencing Junctions 

      Q = + RT_4 - RT_1

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Q        is output
      !P        is output

      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PowerMeas_2Out()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Declarations 
!---------------------------------------


! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number
      INTEGER ISTXFRF

                                                  ! Storage Indices
!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

      ISTXFRF   = NSTXFRF
      NSTXFRF   = NSTXFRF + 14
!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PowerMeas_2Dyn_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! BlackBox generated rtc passive branch calls 
!---------------------------------------

! 1:[rtcbranch] Runtime Configurable Passive Branch
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 


! 30:[datatap] Scalar/Array Tap 


! 50:[datatap] Scalar/Array Tap 


! 60:[datatap] Scalar/Array Tap 


! 70:[mult] Multiplier 


! 80:[mult] Multiplier 


! 90:[mult] Multiplier 


! 100:[mult] Multiplier 


! 110:[sumjct] Summing/Differencing Junctions 


! 120:[sumjct] Summing/Differencing Junctions 


      RETURN
      END

!=======================================================================

      SUBROUTINE Blackbox_PowerMeas_2Out_Begin()

!---------------------------------------
! Standard Header Files 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Declarations 
!---------------------------------------


! Subroutine Arguments

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! RunTime
                                                  !  configuration call
                                                  !  number


!---------------------------------------
! Local Indices 
!---------------------------------------


! Disable runTime configuration call number.

      ICALL_NO  = -1


! Increment dsdyn <--> dsout transfer indices

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


      RETURN
      END

